import type { ColumnType } from "kysely";
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type ChannelImportBatch = {
    id: Generated<string>;
    channel: string;
    filename: string;
    rowsTotal: number;
    rowsImported: number;
    rowsSkipped: number;
    rowsUpdated: number;
    errors: string | null;
    dateRangeStart: Timestamp | null;
    dateRangeEnd: Timestamp | null;
    importedAt: Generated<Timestamp>;
    importedBy: string | null;
    importType: Generated<string>;
    ordersCreated: Generated<number>;
    ordersUpdated: Generated<number>;
};
export type ChannelOrderLine = {
    id: Generated<string>;
    channel: string;
    channelOrderId: string;
    channelRef: string | null;
    channelItemId: string;
    orderDate: Timestamp;
    orderType: string;
    financialStatus: string | null;
    fulfillmentStatus: string | null;
    skuCode: string;
    channelSkuCode: string | null;
    skuTitle: string | null;
    quantity: Generated<number>;
    mrp: number | null;
    sellerPrice: number | null;
    buyerPrice: number | null;
    itemTotal: number | null;
    itemDiscount: number | null;
    orderTotal: number | null;
    taxPercent: number | null;
    taxType: string | null;
    taxAmount: number | null;
    courierName: string | null;
    trackingNumber: string | null;
    dispatchByDate: Timestamp | null;
    dispatchDate: Timestamp | null;
    manifestedDate: Timestamp | null;
    deliveryDate: Timestamp | null;
    returnDate: Timestamp | null;
    channelReturnDate: Timestamp | null;
    customerName: string | null;
    customerCity: string | null;
    customerState: string | null;
    customerZip: string | null;
    invoiceNumber: string | null;
    batchNo: string | null;
    hsnCode: string | null;
    orderId: string | null;
    orderLineId: string | null;
    importedAt: Generated<Timestamp>;
    importBatchId: string | null;
};
export type ComponentRole = {
    id: Generated<string>;
    typeId: string;
    code: string;
    name: string;
    isRequired: Generated<boolean>;
    allowMultiple: Generated<boolean>;
    defaultQuantity: number | null;
    defaultUnit: string | null;
    sortOrder: Generated<number>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ComponentType = {
    id: Generated<string>;
    code: string;
    name: string;
    trackInventory: Generated<boolean>;
    sortOrder: Generated<number>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type CostConfig = {
    id: Generated<string>;
    laborRatePerMin: Generated<number>;
    defaultPackagingCost: Generated<number>;
    lastUpdated: Generated<Timestamp>;
    gstRateAbove: Generated<number>;
    gstRateBelow: Generated<number>;
    gstThreshold: Generated<number>;
    monthlyLaborOverhead: number | null;
    monthlyMarketingBudget: number | null;
};
export type Customer = {
    id: Generated<string>;
    shopifyCustomerId: string | null;
    email: string;
    phone: string | null;
    firstName: string | null;
    lastName: string | null;
    defaultAddress: string | null;
    tags: string | null;
    acceptsMarketing: Generated<boolean>;
    firstOrderDate: Timestamp | null;
    lastOrderDate: Timestamp | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
    exchangeCount: Generated<number>;
    returnCount: Generated<number>;
    rtoCount: Generated<number>;
    rtoOrderCount: Generated<number>;
    rtoValue: Generated<string>;
    orderCount: Generated<number>;
    tier: Generated<string>;
    ltv: Generated<number>;
};
export type Fabric = {
    id: Generated<string>;
    name: string;
    colorName: string;
    standardColor: string | null;
    colorHex: string | null;
    costPerUnit: number | null;
    supplierId: string | null;
    leadTimeDays: number | null;
    minOrderQty: number | null;
    isActive: Generated<boolean>;
    materialId: string | null;
    constructionType: string | null;
    pattern: string | null;
    weight: number | null;
    weightUnit: string | null;
    composition: string | null;
    avgShrinkagePct: number | null;
    defaultLeadTimeDays: number | null;
    defaultMinOrderQty: number | null;
    unit: string | null;
};
export type FabricColour = {
    id: Generated<string>;
    fabricId: string;
    code: string | null;
    colourName: string;
    standardColour: string | null;
    colourHex: string | null;
    costPerUnit: number | null;
    supplierId: string | null;
    leadTimeDays: number | null;
    minOrderQty: number | null;
    currentBalance: Generated<number>;
    isOutOfStock: Generated<boolean>;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type FabricColourReconciliation = {
    id: Generated<string>;
    reconcileDate: Generated<Timestamp>;
    status: Generated<string>;
    notes: string | null;
    createdBy: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type FabricColourReconciliationItem = {
    id: Generated<string>;
    reconciliationId: string;
    fabricColourId: string;
    systemQty: number;
    physicalQty: number | null;
    variance: number | null;
    adjustmentReason: string | null;
    notes: string | null;
    txnId: string | null;
};
export type FabricColourTransaction = {
    id: Generated<string>;
    fabricColourId: string;
    txnType: string;
    qty: number;
    unit: string;
    reason: string;
    costPerUnit: number | null;
    supplierId: string | null;
    referenceId: string | null;
    notes: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
};
export type FabricInvoice = {
    id: Generated<string>;
    invoiceNumber: string | null;
    invoiceDate: Timestamp | null;
    supplierId: string | null;
    supplierName: string | null;
    subtotal: number | null;
    gstAmount: number | null;
    totalAmount: number | null;
    fileData: Buffer;
    fileName: string;
    fileMimeType: string;
    fileSizeBytes: number;
    status: Generated<string>;
    aiRawResponse: unknown | null;
    aiModel: string | null;
    aiConfidence: number | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type FabricInvoiceLine = {
    id: Generated<string>;
    invoiceId: string;
    description: string | null;
    hsnCode: string | null;
    qty: number | null;
    unit: string | null;
    rate: number | null;
    amount: number | null;
    gstPercent: number | null;
    gstAmount: number | null;
    fabricColourId: string | null;
    matchedTxnId: string | null;
    matchType: string | null;
};
export type FabricOrder = {
    id: Generated<string>;
    fabricId: string;
    supplierId: string;
    qtyOrdered: number;
    unit: string;
    costPerUnit: number;
    totalCost: number;
    orderDate: Generated<Timestamp>;
    expectedDate: Timestamp | null;
    receivedDate: Timestamp | null;
    qtyReceived: number | null;
    status: Generated<string>;
    notes: string | null;
};
export type FabricReconciliation = {
    id: Generated<string>;
    reconcileDate: Generated<Timestamp>;
    status: Generated<string>;
    notes: string | null;
    createdBy: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type FabricReconciliationItem = {
    id: Generated<string>;
    reconciliationId: string;
    fabricId: string;
    systemQty: number;
    physicalQty: number | null;
    variance: number | null;
    adjustmentReason: string | null;
    notes: string | null;
    txnId: string | null;
};
export type FailedSyncItem = {
    id: Generated<string>;
    itemType: string;
    resourceId: string;
    rawData: string | null;
    error: string;
    retryCount: Generated<number>;
    maxRetries: Generated<number>;
    nextRetryAt: Timestamp | null;
    status: Generated<string>;
    resolvedAt: Timestamp | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type Feedback = {
    id: Generated<string>;
    customerId: string | null;
    orderId: string | null;
    orderLineId: string | null;
    source: string;
    feedbackType: string;
    status: Generated<string>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type FeedbackContent = {
    id: Generated<string>;
    feedbackId: string;
    title: string | null;
    body: string | null;
    pros: string | null;
    cons: string | null;
    wouldRecommend: boolean | null;
};
export type FeedbackMedia = {
    id: Generated<string>;
    feedbackId: string;
    mediaType: string;
    url: string;
    caption: string | null;
};
export type FeedbackProductLink = {
    id: Generated<string>;
    feedbackId: string;
    productId: string | null;
    variationId: string | null;
    skuId: string | null;
};
export type FeedbackRating = {
    id: Generated<string>;
    feedbackId: string;
    dimension: string;
    score: number;
};
export type FeedbackTag = {
    id: Generated<string>;
    feedbackId: string;
    tag: string;
};
export type InventoryReconciliation = {
    id: Generated<string>;
    reconcileDate: Generated<Timestamp>;
    status: Generated<string>;
    notes: string | null;
    createdBy: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type InventoryReconciliationItem = {
    id: Generated<string>;
    reconciliationId: string;
    skuId: string;
    systemQty: number;
    physicalQty: number | null;
    variance: number | null;
    adjustmentReason: string | null;
    notes: string | null;
    txnId: string | null;
};
export type InventoryTransaction = {
    id: Generated<string>;
    skuId: string;
    txnType: string;
    qty: number;
    reason: string;
    referenceId: string | null;
    notes: string | null;
    warehouseLocation: string | null;
    source: string | null;
    destination: string | null;
    tailorNumber: string | null;
    performedBy: string | null;
    repackingBarcode: string | null;
    userNotes: string | null;
    orderNotes: string | null;
    cohNotes: string | null;
    orderNumber: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
};
export type Invoice = {
    id: Generated<string>;
    invoiceNumber: string | null;
    type: string;
    category: string;
    status: Generated<string>;
    invoiceDate: Timestamp | null;
    dueDate: Timestamp | null;
    supplierId: string | null;
    vendorId: string | null;
    customerId: string | null;
    counterpartyName: string | null;
    subtotal: number | null;
    gstAmount: number | null;
    totalAmount: number;
    paidAmount: Generated<number>;
    balanceDue: Generated<number>;
    orderId: string | null;
    fabricInvoiceId: string | null;
    fileData: Buffer | null;
    fileName: string | null;
    fileMimeType: string | null;
    fileSizeBytes: number | null;
    aiRawResponse: unknown | null;
    aiModel: string | null;
    aiConfidence: number | null;
    ledgerEntryId: string | null;
    notes: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type InvoiceLine = {
    id: Generated<string>;
    invoiceId: string;
    description: string | null;
    hsnCode: string | null;
    qty: number | null;
    unit: string | null;
    rate: number | null;
    amount: number | null;
    gstPercent: number | null;
    gstAmount: number | null;
};
export type LedgerAccount = {
    id: Generated<string>;
    code: string;
    name: string;
    type: string;
    balance: Generated<number>;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type LedgerEntry = {
    id: Generated<string>;
    entryDate: Timestamp;
    description: string;
    sourceType: string;
    sourceId: string | null;
    isReversed: Generated<boolean>;
    reversedById: string | null;
    notes: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type LedgerEntryLine = {
    id: Generated<string>;
    entryId: string;
    accountId: string;
    debit: Generated<number>;
    credit: Generated<number>;
    description: string | null;
};
export type Material = {
    id: Generated<string>;
    name: string;
    description: string | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type MonthlyStockSnapshot = {
    id: Generated<string>;
    skuId: string;
    month: Timestamp;
    openingStock: number;
    totalInward: number;
    totalOutward: number;
    closingStock: number;
    inwardBreakdown: Generated<unknown>;
    outwardBreakdown: Generated<unknown>;
    computedAt: Generated<Timestamp>;
};
export type Order = {
    id: Generated<string>;
    orderNumber: string;
    shopifyOrderId: string | null;
    channel: Generated<string>;
    customerId: string | null;
    customerName: string;
    customerEmail: string | null;
    customerPhone: string | null;
    shippingAddress: string | null;
    orderDate: Generated<Timestamp>;
    internalNotes: string | null;
    paymentMethod: string | null;
    status: Generated<string>;
    isArchived: Generated<boolean>;
    archivedAt: Timestamp | null;
    releasedToShipped: Generated<boolean>;
    releasedToCancelled: Generated<boolean>;
    totalAmount: number;
    createdAt: Generated<Timestamp>;
    syncedAt: Timestamp | null;
    codRemittanceUtr: string | null;
    codRemittedAmount: number | null;
    codRemittedAt: Timestamp | null;
    codShopifySyncError: string | null;
    codShopifySyncStatus: string | null;
    codShopifySyncedAt: Timestamp | null;
    isExchange: Generated<boolean>;
    originalOrderId: string | null;
    shipByDate: Timestamp | null;
    sheetPushedAt: Timestamp | null;
    partiallyCancelled: Generated<boolean>;
    paymentConfirmedAt: Timestamp | null;
    paymentConfirmedBy: string | null;
    paymentStatus: Generated<string | null>;
    channelOrderId: string | null;
};
export type OrderLine = {
    id: Generated<string>;
    orderId: string;
    shopifyLineId: string | null;
    skuId: string;
    qty: number;
    unitPrice: number;
    lineStatus: Generated<string>;
    allocatedAt: Timestamp | null;
    pickedAt: Timestamp | null;
    packedAt: Timestamp | null;
    shippedAt: Timestamp | null;
    deliveredAt: Timestamp | null;
    inventoryTxnId: string | null;
    productionBatchId: string | null;
    notes: string | null;
    awbNumber: string | null;
    courier: string | null;
    trackingStatus: string | null;
    lastTrackingUpdate: Timestamp | null;
    lastScanAt: Timestamp | null;
    lastScanLocation: string | null;
    lastScanStatus: string | null;
    courierStatusCode: string | null;
    deliveryAttempts: number | null;
    expectedDeliveryDate: Timestamp | null;
    rtoInitiatedAt: Timestamp | null;
    rtoReceivedAt: Timestamp | null;
    rtoCondition: string | null;
    rtoInwardedAt: Timestamp | null;
    rtoInwardedById: string | null;
    rtoNotes: string | null;
    customizedAt: Timestamp | null;
    customizedById: string | null;
    isCustomized: Generated<boolean>;
    isNonReturnable: Generated<boolean>;
    originalSkuId: string | null;
    refundAmount: number | null;
    refundNotes: string | null;
    refundReason: string | null;
    refundedAt: Timestamp | null;
    shippingAddress: string | null;
    channelFulfillmentStatus: string | null;
    channelItemId: string | null;
    returnBatchNumber: string | null;
    returnStatus: string | null;
    returnQty: number | null;
    returnRequestedAt: Timestamp | null;
    returnRequestedById: string | null;
    returnPickupType: string | null;
    returnAwbNumber: string | null;
    returnCourier: string | null;
    returnPickupScheduledAt: Timestamp | null;
    returnPickupAt: Timestamp | null;
    returnReceivedAt: Timestamp | null;
    returnReceivedById: string | null;
    returnCondition: string | null;
    returnConditionNotes: string | null;
    returnReasonCategory: string | null;
    returnReasonDetail: string | null;
    returnResolution: string | null;
    returnGrossAmount: string | null;
    returnDiscountClawback: string | null;
    returnDeductions: string | null;
    returnDeductionNotes: string | null;
    returnNetAmount: string | null;
    returnRefundLinkSentAt: Timestamp | null;
    returnRefundLinkId: string | null;
    returnRefundCompletedAt: Timestamp | null;
    returnRefundMethod: string | null;
    returnRefundReference: string | null;
    returnExchangeOrderId: string | null;
    returnExchangeSkuId: string | null;
    returnExchangePriceDiff: string | null;
    returnClosedManually: boolean | null;
    returnClosedManuallyAt: Timestamp | null;
    returnClosedManuallyById: string | null;
    returnClosedReason: string | null;
    returnNotes: string | null;
    returnPrimeRequestId: string | null;
    returnPrimeRequestNumber: string | null;
    returnPrimeStatus: string | null;
    returnPrimeCreatedAt: Timestamp | null;
    returnPrimeUpdatedAt: Timestamp | null;
    returnPrimeSyncedAt: Timestamp | null;
    returnPrimeSyncError: string | null;
};
export type OrderPayment = {
    id: Generated<string>;
    orderId: string;
    amount: number;
    paymentMethod: string | null;
    reference: string | null;
    notes: string | null;
    recordedById: string;
    recordedAt: Generated<Timestamp>;
    createdAt: Generated<Timestamp>;
};
export type Payment = {
    id: Generated<string>;
    referenceNumber: string | null;
    direction: string;
    method: string;
    status: Generated<string>;
    amount: number;
    matchedAmount: Generated<number>;
    unmatchedAmount: Generated<number>;
    paymentDate: Timestamp;
    supplierId: string | null;
    vendorId: string | null;
    customerId: string | null;
    counterpartyName: string | null;
    fileData: Buffer | null;
    fileName: string | null;
    fileMimeType: string | null;
    fileSizeBytes: number | null;
    ledgerEntryId: string | null;
    notes: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type PaymentInvoice = {
    id: Generated<string>;
    paymentId: string;
    invoiceId: string;
    amount: number;
    notes: string | null;
    matchedAt: Generated<Timestamp>;
    matchedById: string;
};
export type Pincode = {
    id: Generated<string>;
    pincode: string;
    district: string;
    state: string;
    region: string | null;
    division: string | null;
    createdAt: Generated<Timestamp>;
};
export type Product = {
    id: Generated<string>;
    name: string;
    styleCode: string | null;
    category: string;
    productType: string;
    gender: Generated<string>;
    baseProductionTimeMins: Generated<number>;
    defaultFabricConsumption: number | null;
    imageUrl: string | null;
    isActive: Generated<boolean>;
    isReturnable: Generated<boolean>;
    nonReturnableReason: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
    shopifyProductId: string | null;
    shopifyHandle: string | null;
    exchangeCount: Generated<number>;
    returnCount: Generated<number>;
    writeOffCount: Generated<number>;
    trimsCost: number | null;
    packagingCost: number | null;
    liningCost: number | null;
    shopifyProductIds: Generated<string[]>;
};
export type ProductBomTemplate = {
    id: Generated<string>;
    productId: string;
    roleId: string;
    trimItemId: string | null;
    serviceItemId: string | null;
    defaultQuantity: Generated<number>;
    quantityUnit: Generated<string>;
    wastagePercent: Generated<number>;
    notes: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ProductionBatch = {
    id: Generated<string>;
    batchCode: string | null;
    batchDate: Generated<Timestamp>;
    tailorId: string | null;
    skuId: string | null;
    sampleCode: string | null;
    sampleName: string | null;
    sampleColour: string | null;
    sampleSize: string | null;
    qtyPlanned: number;
    qtyCompleted: Generated<number>;
    priority: string;
    sourceOrderLineId: string | null;
    status: Generated<string>;
    notes: string | null;
    createdAt: Generated<Timestamp>;
    completedAt: Timestamp | null;
};
export type RepackingQueueItem = {
    id: Generated<string>;
    skuId: string;
    qty: Generated<number>;
    returnRequestId: string | null;
    returnLineId: string | null;
    status: Generated<string>;
    condition: string;
    inspectionNotes: string | null;
    writeOffReason: string | null;
    createdAt: Generated<Timestamp>;
    processedAt: Timestamp | null;
    processedById: string | null;
    qcComments: string | null;
    orderLineId: string | null;
};
export type ReplacementItem = {
    id: Generated<string>;
    requestId: string;
    skuId: string;
    qty: number;
    unitPrice: number;
};
export type ReturnPrimeRequest = {
    id: Generated<string>;
    rpRequestId: string;
    rpRequestNumber: string;
    requestType: string;
    shopifyOrderId: string | null;
    shopifyOrderName: string | null;
    orderId: string | null;
    customerName: string | null;
    customerEmail: string | null;
    customerPhone: string | null;
    customerAddress: unknown | null;
    customerBank: unknown | null;
    isApproved: Generated<boolean>;
    approvedAt: Timestamp | null;
    approvedComment: string | null;
    isReceived: Generated<boolean>;
    receivedAt: Timestamp | null;
    receivedComment: string | null;
    isInspected: Generated<boolean>;
    inspectedAt: Timestamp | null;
    inspectedComment: string | null;
    isRefunded: Generated<boolean>;
    refundedAt: Timestamp | null;
    isRejected: Generated<boolean>;
    rejectedAt: Timestamp | null;
    rejectedComment: string | null;
    isArchived: Generated<boolean>;
    archivedAt: Timestamp | null;
    lineItems: Generated<unknown>;
    lineItemCount: Generated<number>;
    totalValue: Generated<string>;
    primaryReason: string | null;
    rpCreatedAt: Timestamp;
    rpUpdatedAt: Timestamp | null;
    syncedAt: Generated<Timestamp>;
    rawData: unknown | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ReturnRequest = {
    id: Generated<string>;
    requestNumber: string;
    requestType: string;
    originalOrderId: string;
    customerId: string | null;
    status: Generated<string>;
    reasonCategory: string;
    reasonDetails: string | null;
    resolutionNotes: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
    exchangeOrderId: string | null;
    forwardDelivered: Generated<boolean>;
    forwardDeliveredAt: Timestamp | null;
    reverseReceived: Generated<boolean>;
    reverseReceivedAt: Timestamp | null;
    forwardShippedAt: Timestamp | null;
    paymentAmount: number | null;
    paymentCollectedAt: Timestamp | null;
    refundAmount: number | null;
    refundProcessedAt: Timestamp | null;
    replacementValue: number | null;
    resolution: Generated<string>;
    returnValue: number | null;
    reverseInTransitAt: Timestamp | null;
    valueDifference: number | null;
};
export type ReturnRequestLine = {
    id: Generated<string>;
    requestId: string;
    originalOrderLineId: string | null;
    skuId: string;
    qty: number;
    exchangeSkuId: string | null;
    exchangeQty: number | null;
    itemCondition: string | null;
    inspectionNotes: string | null;
    unitPrice: number | null;
};
export type ReturnSettings = {
    id: Generated<string>;
    /**
     * Days from delivery within which returns are accepted
     */
    windowDays: Generated<number>;
    /**
     * Days before window expiry to show warning (e.g., 12 means 2 days left warning)
     */
    windowWarningDays: Generated<number>;
    /**
     * Auto-reject returns after this many days (null = allow with override)
     */
    autoRejectAfterDays: number | null;
    /**
     * Allow returns after window expires with manual override
     */
    allowExpiredOverride: Generated<boolean>;
    updatedAt: Timestamp;
    updatedById: string | null;
};
export type ReturnShipping = {
    id: Generated<string>;
    requestId: string;
    direction: string;
    courier: string | null;
    awbNumber: string | null;
    pickupAddress: string | null;
    pickupScheduledAt: Timestamp | null;
    pickedUpAt: Timestamp | null;
    receivedAt: Timestamp | null;
    shippedAt: Timestamp | null;
    deliveredAt: Timestamp | null;
    status: Generated<string>;
    notes: string | null;
};
export type ReturnStatusHistory = {
    id: Generated<string>;
    requestId: string;
    fromStatus: string;
    toStatus: string;
    changedById: string;
    notes: string | null;
    createdAt: Generated<Timestamp>;
};
export type Role = {
    id: Generated<string>;
    name: string;
    displayName: string;
    description: string | null;
    permissions: unknown;
    isBuiltIn: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ServiceItem = {
    id: Generated<string>;
    code: string;
    name: string;
    category: string;
    description: string | null;
    costPerJob: number;
    costUnit: Generated<string>;
    vendorId: string | null;
    leadTimeDays: number | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ShopifyInventoryCache = {
    skuId: string;
    shopifyInventoryItemId: string;
    availableQty: number;
    lastSynced: Generated<Timestamp>;
};
export type ShopifyOrderCache = {
    id: string;
    rawData: string;
    orderNumber: string | null;
    financialStatus: string | null;
    fulfillmentStatus: string | null;
    lastWebhookAt: Generated<Timestamp>;
    webhookTopic: string | null;
    processedAt: Timestamp | null;
    processingError: string | null;
    createdAt: Generated<Timestamp>;
    customerNotes: string | null;
    discountCodes: string | null;
    paymentMethod: string | null;
    shippedAt: Timestamp | null;
    shippingCity: string | null;
    shippingCountry: string | null;
    shippingState: string | null;
    tags: string | null;
    trackingCompany: string | null;
    trackingNumber: string | null;
    trackingUrl: string | null;
    deliveredAt: Timestamp | null;
    fulfillmentUpdatedAt: Timestamp | null;
    shipmentStatus: string | null;
    processingLock: Timestamp | null;
    billingCity: string | null;
    billingName: string | null;
    billingPhone: string | null;
    billingState: string | null;
    billingZip: string | null;
    buyerAcceptsMarketing: boolean | null;
    cancelReason: string | null;
    confirmationNumber: string | null;
    currency: string | null;
    customerEmail: string | null;
    customerFirstName: string | null;
    customerId: string | null;
    customerLastName: string | null;
    customerPhone: string | null;
    fulfillmentCount: number | null;
    isConfirmed: boolean | null;
    isTaxExempt: boolean | null;
    isTest: boolean | null;
    lineItemCount: number | null;
    paymentGatewayNames: string | null;
    refundCount: number | null;
    shippingAddress1: string | null;
    shippingAddress2: string | null;
    shippingCountryCode: string | null;
    shippingLatitude: number | null;
    shippingLongitude: number | null;
    shippingName: string | null;
    shippingPhone: string | null;
    shippingProvince: string | null;
    shippingProvinceCode: string | null;
    shippingZip: string | null;
    shopifyCancelledAt: Timestamp | null;
    shopifyClosedAt: Timestamp | null;
    shopifyCreatedAt: Timestamp | null;
    shopifyOrderName: string | null;
    shopifyProcessedAt: Timestamp | null;
    shopifyUpdatedAt: Timestamp | null;
    sourceName: string | null;
    totalLineItemsPrice: number | null;
    totalOutstanding: number | null;
    totalShippingPrice: number | null;
    totalPrice: string | null;
    subtotalPrice: string | null;
    totalTax: string | null;
    totalDiscounts: string | null;
    lineItemsJson: string | null;
    shippingLinesJson: string | null;
    taxLinesJson: string | null;
    noteAttributesJson: string | null;
    billingAddress1: string | null;
    billingAddress2: string | null;
    billingCountry: string | null;
    billingCountryCode: string | null;
};
export type ShopifyProductCache = {
    id: string;
    rawData: string;
    title: string | null;
    handle: string | null;
    lastWebhookAt: Generated<Timestamp>;
    webhookTopic: string | null;
    processedAt: Timestamp | null;
    processingError: string | null;
    createdAt: Generated<Timestamp>;
};
export type Sku = {
    id: Generated<string>;
    skuCode: string;
    variationId: string;
    size: string;
    fabricConsumption: Generated<number>;
    mrp: number;
    currentBalance: Generated<number>;
    targetStockQty: Generated<number>;
    targetStockMethod: Generated<string>;
    isActive: Generated<boolean>;
    shopifyInventoryItemId: string | null;
    shopifyVariantId: string | null;
    exchangeCount: Generated<number>;
    returnCount: Generated<number>;
    writeOffCount: Generated<number>;
    customizationCount: Generated<number>;
    customizationNotes: string | null;
    customizationType: string | null;
    customizationValue: string | null;
    isCustomSku: Generated<boolean>;
    linkedOrderLineId: string | null;
    parentSkuId: string | null;
    trimsCost: number | null;
    packagingCost: number | null;
    liningCost: number | null;
    laborMinutes: number | null;
    bomCost: number | null;
};
export type SkuBomLine = {
    id: Generated<string>;
    skuId: string;
    roleId: string;
    fabricColourId: string | null;
    trimItemId: string | null;
    serviceItemId: string | null;
    quantity: number | null;
    wastagePercent: number | null;
    overrideCost: number | null;
    notes: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type SkuCosting = {
    skuId: string;
    fabricCost: number;
    laborTimeMins: number;
    laborRatePerMin: number;
    laborCost: number;
    packagingCost: Generated<number>;
    otherCost: Generated<number>;
    totalCogs: number;
    lastUpdated: Generated<Timestamp>;
};
export type Supplier = {
    id: Generated<string>;
    name: string;
    contactName: string | null;
    email: string | null;
    phone: string | null;
    address: string | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
};
export type SyncJob = {
    id: Generated<string>;
    jobType: string;
    status: Generated<string>;
    dateFilter: string | null;
    daysBack: number | null;
    syncMode: string | null;
    staleAfterMins: number | null;
    totalRecords: number | null;
    processed: Generated<number>;
    created: Generated<number>;
    updated: Generated<number>;
    skipped: Generated<number>;
    errors: Generated<number>;
    lastProcessedId: string | null;
    currentBatch: Generated<number>;
    errorLog: string | null;
    lastError: string | null;
    startedAt: Timestamp | null;
    completedAt: Timestamp | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type SystemSetting = {
    key: string;
    value: string;
    updatedAt: Timestamp;
};
export type Tailor = {
    id: Generated<string>;
    name: string;
    specializations: string | null;
    dailyCapacityMins: Generated<number>;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
};
export type TrackingApiResponse = {
    id: Generated<string>;
    awbNumber: string;
    source: string;
    statusCode: number;
    response: unknown;
    createdAt: Generated<Timestamp>;
};
export type TrimItem = {
    id: Generated<string>;
    code: string;
    name: string;
    category: string;
    description: string | null;
    costPerUnit: number;
    unit: Generated<string>;
    supplierId: string | null;
    minOrderQty: number | null;
    leadTimeDays: number | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type User = {
    id: Generated<string>;
    email: string;
    password: string;
    name: string;
    role: Generated<string>;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
    mustChangePassword: Generated<boolean>;
    roleId: string | null;
    tokenVersion: Generated<number>;
    extraAccess: Generated<unknown>;
};
export type UserGridPreference = {
    id: Generated<string>;
    userId: string;
    gridId: string;
    visibleColumns: string;
    columnOrder: string;
    columnWidths: string;
    adminVersion: Timestamp | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type UserPermissionOverride = {
    id: Generated<string>;
    userId: string;
    permission: string;
    granted: boolean;
    createdAt: Generated<Timestamp>;
};
export type Variation = {
    id: Generated<string>;
    productId: string;
    colorName: string;
    standardColor: string | null;
    colorHex: string | null;
    imageUrl: string | null;
    isActive: Generated<boolean>;
    hasLining: Generated<boolean>;
    trimsCost: number | null;
    packagingCost: number | null;
    liningCost: number | null;
    laborMinutes: number | null;
    bomCost: number | null;
    shopifySourceProductId: string | null;
    shopifySourceHandle: string | null;
};
export type VariationBomLine = {
    id: Generated<string>;
    variationId: string;
    roleId: string;
    fabricColourId: string | null;
    trimItemId: string | null;
    serviceItemId: string | null;
    quantity: number | null;
    wastagePercent: number | null;
    notes: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type Vendor = {
    id: Generated<string>;
    name: string;
    contactName: string | null;
    email: string | null;
    phone: string | null;
    address: string | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type WebhookLog = {
    id: Generated<string>;
    webhookId: string;
    topic: string;
    resourceId: string | null;
    source: Generated<string>;
    status: Generated<string>;
    responseCode: number | null;
    processingTime: number | null;
    error: string | null;
    payload: string | null;
    resultData: string | null;
    receivedAt: Generated<Timestamp>;
    processedAt: Timestamp | null;
};
export type WorkerRun = {
    id: Generated<string>;
    workerName: string;
    status: Generated<string>;
    startedAt: Timestamp;
    completedAt: Timestamp | null;
    durationMs: number | null;
    result: unknown | null;
    error: string | null;
    triggeredBy: Generated<string>;
    createdAt: Generated<Timestamp>;
};
export type WriteOffLog = {
    id: Generated<string>;
    skuId: string;
    qty: number;
    reason: string;
    sourceType: string;
    sourceId: string | null;
    notes: string | null;
    costValue: number | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
};
export type DB = {
    ChannelImportBatch: ChannelImportBatch;
    ChannelOrderLine: ChannelOrderLine;
    ComponentRole: ComponentRole;
    ComponentType: ComponentType;
    CostConfig: CostConfig;
    Customer: Customer;
    Fabric: Fabric;
    FabricColour: FabricColour;
    FabricColourReconciliation: FabricColourReconciliation;
    FabricColourReconciliationItem: FabricColourReconciliationItem;
    FabricColourTransaction: FabricColourTransaction;
    FabricInvoice: FabricInvoice;
    FabricInvoiceLine: FabricInvoiceLine;
    FabricOrder: FabricOrder;
    FabricReconciliation: FabricReconciliation;
    FabricReconciliationItem: FabricReconciliationItem;
    FailedSyncItem: FailedSyncItem;
    Feedback: Feedback;
    FeedbackContent: FeedbackContent;
    FeedbackMedia: FeedbackMedia;
    FeedbackProductLink: FeedbackProductLink;
    FeedbackRating: FeedbackRating;
    FeedbackTag: FeedbackTag;
    InventoryReconciliation: InventoryReconciliation;
    InventoryReconciliationItem: InventoryReconciliationItem;
    InventoryTransaction: InventoryTransaction;
    Invoice: Invoice;
    InvoiceLine: InvoiceLine;
    LedgerAccount: LedgerAccount;
    LedgerEntry: LedgerEntry;
    LedgerEntryLine: LedgerEntryLine;
    Material: Material;
    MonthlyStockSnapshot: MonthlyStockSnapshot;
    Order: Order;
    OrderLine: OrderLine;
    OrderPayment: OrderPayment;
    Payment: Payment;
    PaymentInvoice: PaymentInvoice;
    Pincode: Pincode;
    Product: Product;
    ProductBomTemplate: ProductBomTemplate;
    ProductionBatch: ProductionBatch;
    RepackingQueueItem: RepackingQueueItem;
    ReplacementItem: ReplacementItem;
    ReturnPrimeRequest: ReturnPrimeRequest;
    ReturnRequest: ReturnRequest;
    ReturnRequestLine: ReturnRequestLine;
    ReturnSettings: ReturnSettings;
    ReturnShipping: ReturnShipping;
    ReturnStatusHistory: ReturnStatusHistory;
    Role: Role;
    ServiceItem: ServiceItem;
    ShopifyInventoryCache: ShopifyInventoryCache;
    ShopifyOrderCache: ShopifyOrderCache;
    ShopifyProductCache: ShopifyProductCache;
    Sku: Sku;
    SkuBomLine: SkuBomLine;
    SkuCosting: SkuCosting;
    Supplier: Supplier;
    SyncJob: SyncJob;
    SystemSetting: SystemSetting;
    Tailor: Tailor;
    TrackingApiResponse: TrackingApiResponse;
    TrimItem: TrimItem;
    User: User;
    UserGridPreference: UserGridPreference;
    UserPermissionOverride: UserPermissionOverride;
    Variation: Variation;
    VariationBomLine: VariationBomLine;
    Vendor: Vendor;
    WebhookLog: WebhookLog;
    WorkerRun: WorkerRun;
    WriteOffLog: WriteOffLog;
};
