import type { ColumnType } from "kysely";
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Allocation = {
    id: Generated<string>;
    paymentId: string | null;
    bankTransactionId: string | null;
    invoiceId: string;
    amount: number;
    notes: string | null;
    matchedAt: Generated<Timestamp>;
    matchedById: string;
};
export type AttendanceRecord = {
    id: Generated<string>;
    employeeId: string;
    date: Timestamp;
    status: string;
    shift: string | null;
    inTime: string | null;
    outTime: string | null;
    lateByMins: Generated<number>;
    earlyByMins: Generated<number>;
    overtimeMins: Generated<number>;
    durationMins: Generated<number>;
    importBatchId: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type Audience = {
    id: Generated<string>;
    name: string;
    description: string | null;
    filters: unknown;
    customerCount: Generated<number>;
    createdById: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type BankImportBatch = {
    id: Generated<string>;
    bank: string;
    fileName: string;
    rowCount: number;
    newCount: number;
    skippedCount: number;
    totalDebits: number;
    totalCredits: number;
    openingBalance: number | null;
    closingBalance: number | null;
    balanceMatched: boolean | null;
    createdAt: Generated<Timestamp>;
};
export type BankTransaction = {
    id: Generated<string>;
    bank: string;
    txnHash: string;
    rawData: unknown;
    txnDate: Timestamp;
    amount: number;
    direction: string;
    narration: string | null;
    reference: string | null;
    utr: string | null;
    closingBalance: number | null;
    period: string | null;
    counterpartyName: string | null;
    debitAccountCode: string | null;
    creditAccountCode: string | null;
    category: string | null;
    partyId: string | null;
    matchedInvoiceId: string | null;
    intendedDebitAccount: string | null;
    postingType: string | null;
    matchedAmount: Generated<number>;
    unmatchedAmount: Generated<number>;
    notes: string | null;
    fileData: Buffer | null;
    filePath: string | null;
    fileName: string | null;
    fileMimeType: string | null;
    fileSizeBytes: number | null;
    driveFileId: string | null;
    driveUrl: string | null;
    driveUploadedAt: Timestamp | null;
    status: Generated<string>;
    skipReason: string | null;
    ledgerEntryId: string | null;
    paymentId: string | null;
    legacySourceId: string | null;
    batchId: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ChannelImportBatch = {
    id: Generated<string>;
    channel: string;
    filename: string;
    rowsTotal: number;
    rowsImported: number;
    rowsSkipped: number;
    rowsUpdated: number;
    errors: string | null;
    dateRangeStart: Timestamp | null;
    dateRangeEnd: Timestamp | null;
    importedAt: Generated<Timestamp>;
    importedBy: string | null;
    importType: Generated<string>;
    ordersCreated: Generated<number>;
    ordersUpdated: Generated<number>;
};
export type ChannelOrderLine = {
    id: Generated<string>;
    channel: string;
    channelOrderId: string;
    channelRef: string | null;
    channelItemId: string;
    orderDate: Timestamp;
    orderType: string;
    financialStatus: string | null;
    fulfillmentStatus: string | null;
    skuCode: string;
    channelSkuCode: string | null;
    skuTitle: string | null;
    quantity: Generated<number>;
    mrp: number | null;
    sellerPrice: number | null;
    buyerPrice: number | null;
    itemTotal: number | null;
    itemDiscount: number | null;
    orderTotal: number | null;
    taxPercent: number | null;
    taxType: string | null;
    taxAmount: number | null;
    courierName: string | null;
    trackingNumber: string | null;
    dispatchByDate: Timestamp | null;
    dispatchDate: Timestamp | null;
    manifestedDate: Timestamp | null;
    deliveryDate: Timestamp | null;
    returnDate: Timestamp | null;
    channelReturnDate: Timestamp | null;
    customerName: string | null;
    customerCity: string | null;
    customerState: string | null;
    customerZip: string | null;
    invoiceNumber: string | null;
    batchNo: string | null;
    hsnCode: string | null;
    orderId: string | null;
    orderLineId: string | null;
    importedAt: Generated<Timestamp>;
    importBatchId: string | null;
};
export type CodRemittance = {
    id: Generated<string>;
    remittanceId: string;
    remittanceDate: Timestamp;
    codGenerated: Generated<number>;
    billAdjusted: Generated<number>;
    refundAdjusted: Generated<number>;
    transactionCharges: Generated<number>;
    transactionGstCharges: Generated<number>;
    walletAmount: Generated<number>;
    advanceHold: Generated<number>;
    codRemitted: Generated<number>;
    orderDetails: unknown | null;
    orderCount: Generated<number>;
    ordersProcessed: Generated<number>;
    source: Generated<string>;
    syncedAt: Generated<Timestamp>;
    bankTransactionId: string | null;
    matchedAt: Timestamp | null;
    matchConfidence: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ComponentRole = {
    id: Generated<string>;
    typeId: string;
    code: string;
    name: string;
    isRequired: Generated<boolean>;
    allowMultiple: Generated<boolean>;
    defaultQuantity: number | null;
    defaultUnit: string | null;
    sortOrder: Generated<number>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ComponentType = {
    id: Generated<string>;
    code: string;
    name: string;
    trackInventory: Generated<boolean>;
    sortOrder: Generated<number>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type CostConfig = {
    id: Generated<string>;
    laborRatePerMin: Generated<number>;
    defaultPackagingCost: Generated<number>;
    lastUpdated: Generated<Timestamp>;
    gstRateAbove: Generated<number>;
    gstRateBelow: Generated<number>;
    gstThreshold: Generated<number>;
    monthlyLaborOverhead: number | null;
    monthlyMarketingBudget: number | null;
};
export type Customer = {
    id: Generated<string>;
    shopifyCustomerId: string | null;
    email: string;
    phone: string | null;
    firstName: string | null;
    lastName: string | null;
    defaultAddress: string | null;
    tags: string | null;
    acceptsMarketing: Generated<boolean>;
    firstOrderDate: Timestamp | null;
    lastOrderDate: Timestamp | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
    exchangeCount: Generated<number>;
    returnCount: Generated<number>;
    rtoCount: Generated<number>;
    rtoOrderCount: Generated<number>;
    rtoValue: Generated<string>;
    orderCount: Generated<number>;
    tier: Generated<string>;
    ltv: Generated<number>;
    storeCreditBalance: Generated<string>;
    bankAccountName: string | null;
    bankAccountNumber: string | null;
    bankIfsc: string | null;
    emailOptOut: Generated<boolean>;
};
export type DemandForecast = {
    id: Generated<string>;
    createdAt: Generated<Timestamp>;
    createdById: string | null;
    /**
     * Number of weeks forecasted
     */
    forecastWeeks: Generated<number>;
    /**
     * Full forecast JSON (products, fabric requirements, purchase orders, etc.)
     */
    data: unknown;
    /**
     * Claude AI analysis text (populated after user requests it)
     */
    aiAnalysis: string | null;
    /**
     * Summary fields for quick listing
     */
    totalUnits: number | null;
    productCount: number | null;
    shortfallCount: number | null;
};
export type DomainEvent = {
    id: Generated<string>;
    domain: string;
    event: string;
    entityType: string;
    entityId: string;
    summary: string;
    meta: unknown | null;
    actorId: string | null;
    createdAt: Generated<Timestamp>;
};
export type EmailCampaign = {
    id: Generated<string>;
    name: string;
    subject: string;
    preheaderText: string | null;
    htmlContent: string | null;
    shopifyProductIds: unknown | null;
    sourceId: string | null;
    status: Generated<string>;
    audienceFilter: unknown | null;
    audienceId: string | null;
    recipientCount: Generated<number>;
    sentCount: Generated<number>;
    deliveredCount: Generated<number>;
    openCount: Generated<number>;
    clickCount: Generated<number>;
    bounceCount: Generated<number>;
    unsubscribeCount: Generated<number>;
    utmSource: Generated<string>;
    utmMedium: Generated<string>;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
    scheduledAt: Timestamp | null;
    sentAt: Timestamp | null;
    createdById: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type EmailCampaignRecipient = {
    id: Generated<string>;
    campaignId: string;
    customerId: string;
    email: string;
    status: Generated<string>;
    sentAt: Timestamp | null;
    deliveredAt: Timestamp | null;
    openedAt: Timestamp | null;
    clickedAt: Timestamp | null;
    emailLogId: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type EmailLog = {
    id: Generated<string>;
    messageId: string | null;
    toEmail: string;
    fromEmail: string;
    subject: string;
    htmlContent: string;
    textContent: string | null;
    provider: string;
    templateKey: string | null;
    status: Generated<string>;
    sentAt: Timestamp | null;
    deliveredAt: Timestamp | null;
    error: string | null;
    entityType: string | null;
    entityId: string | null;
    metadata: unknown | null;
    createdById: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type Employee = {
    id: Generated<string>;
    name: string;
    employeeCode: string | null;
    phone: string | null;
    email: string | null;
    /**
     * Personal details (compliance: PF Form 11, ESIC Form 1)
     */
    dateOfBirth: Timestamp | null;
    gender: string | null;
    fatherOrSpouseName: string | null;
    maritalStatus: string | null;
    currentAddress: string | null;
    permanentAddress: string | null;
    emergencyContactName: string | null;
    emergencyContactPhone: string | null;
    emergencyContactRelation: string | null;
    dateOfJoining: Timestamp | null;
    dateOfExit: Timestamp | null;
    department: string;
    designation: string | null;
    /**
     * Basic salary — HRA (40%), Other (60%), Gross (2x basic) are always computed
     */
    basicSalary: number;
    /**
     * Statutory deduction flags
     */
    pfApplicable: Generated<boolean>;
    esicApplicable: Generated<boolean>;
    ptApplicable: Generated<boolean>;
    /**
     * Bank details
     */
    bankAccountName: string | null;
    bankAccountNumber: string | null;
    bankIfsc: string | null;
    bankName: string | null;
    /**
     * Statutory IDs
     */
    pan: string | null;
    aadhaar: string | null;
    uan: string | null;
    pfNumber: string | null;
    esicNumber: string | null;
    notes: string | null;
    /**
     * Links to other models
     */
    partyId: string | null;
    tailorId: string | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type Fabric = {
    id: Generated<string>;
    name: string;
    colorName: Generated<string>;
    standardColor: string | null;
    colorHex: string | null;
    costPerUnit: number | null;
    partyId: string | null;
    isActive: Generated<boolean>;
    materialId: string | null;
    constructionType: string | null;
    pattern: string | null;
    weight: number | null;
    weightUnit: string | null;
    composition: string | null;
    avgShrinkagePct: number | null;
    defaultLeadTimeDays: number | null;
    defaultMinOrderQty: number | null;
    unit: string | null;
};
export type FabricColour = {
    id: Generated<string>;
    fabricId: string;
    code: string | null;
    colourName: string;
    standardColour: string | null;
    colourHex: string | null;
    costPerUnit: number | null;
    partyId: string | null;
    leadTimeDays: number | null;
    minOrderQty: number | null;
    currentBalance: Generated<number>;
    isOutOfStock: Generated<boolean>;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type FabricColourReconciliation = {
    id: Generated<string>;
    reconcileDate: Generated<Timestamp>;
    status: Generated<string>;
    notes: string | null;
    createdBy: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type FabricColourReconciliationItem = {
    id: Generated<string>;
    reconciliationId: string;
    fabricColourId: string;
    systemQty: number;
    physicalQty: number | null;
    variance: number | null;
    adjustmentReason: string | null;
    notes: string | null;
    txnId: string | null;
};
export type FabricColourTransaction = {
    id: Generated<string>;
    fabricColourId: string;
    txnType: string;
    qty: number;
    unit: string;
    reason: string;
    costPerUnit: number | null;
    partyId: string | null;
    referenceId: string | null;
    notes: string | null;
    receiptDate: Timestamp | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
};
export type FabricOrder = {
    id: Generated<string>;
    fabricId: string;
    partyId: string;
    qtyOrdered: number;
    unit: string;
    costPerUnit: number;
    totalCost: number;
    orderDate: Generated<Timestamp>;
    expectedDate: Timestamp | null;
    receivedDate: Timestamp | null;
    qtyReceived: number | null;
    status: Generated<string>;
    notes: string | null;
};
export type FabricReconciliation = {
    id: Generated<string>;
    reconcileDate: Generated<Timestamp>;
    status: Generated<string>;
    notes: string | null;
    createdBy: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type FabricReconciliationItem = {
    id: Generated<string>;
    reconciliationId: string;
    fabricId: string;
    systemQty: number;
    physicalQty: number | null;
    variance: number | null;
    adjustmentReason: string | null;
    notes: string | null;
    txnId: string | null;
};
export type FabricStockCount = {
    id: Generated<string>;
    fabricColourId: string;
    physicalQty: number;
    countedById: string;
    countedAt: Generated<Timestamp>;
    status: Generated<string>;
    notes: string | null;
};
export type FailedSyncItem = {
    id: Generated<string>;
    itemType: string;
    resourceId: string;
    rawData: string | null;
    error: string;
    retryCount: Generated<number>;
    maxRetries: Generated<number>;
    nextRetryAt: Timestamp | null;
    status: Generated<string>;
    resolvedAt: Timestamp | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type Feedback = {
    id: Generated<string>;
    customerId: string | null;
    orderId: string | null;
    orderLineId: string | null;
    source: string;
    feedbackType: string;
    status: Generated<string>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type FeedbackContent = {
    id: Generated<string>;
    feedbackId: string;
    title: string | null;
    body: string | null;
    pros: string | null;
    cons: string | null;
    wouldRecommend: boolean | null;
};
export type FeedbackMedia = {
    id: Generated<string>;
    feedbackId: string;
    mediaType: string;
    url: string;
    caption: string | null;
};
export type FeedbackProductLink = {
    id: Generated<string>;
    feedbackId: string;
    productId: string | null;
    variationId: string | null;
    skuId: string | null;
};
export type FeedbackRating = {
    id: Generated<string>;
    feedbackId: string;
    dimension: string;
    score: number;
};
export type FeedbackTag = {
    id: Generated<string>;
    feedbackId: string;
    tag: string;
};
export type InventoryReconciliation = {
    id: Generated<string>;
    reconcileDate: Generated<Timestamp>;
    status: Generated<string>;
    notes: string | null;
    createdBy: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type InventoryReconciliationItem = {
    id: Generated<string>;
    reconciliationId: string;
    skuId: string;
    systemQty: number;
    physicalQty: number | null;
    variance: number | null;
    adjustmentReason: string | null;
    notes: string | null;
    txnId: string | null;
};
export type InventoryTransaction = {
    id: Generated<string>;
    skuId: string;
    txnType: string;
    qty: number;
    reason: string;
    referenceId: string | null;
    notes: string | null;
    warehouseLocation: string | null;
    source: string | null;
    destination: string | null;
    tailorNumber: string | null;
    performedBy: string | null;
    repackingBarcode: string | null;
    userNotes: string | null;
    orderNotes: string | null;
    cohNotes: string | null;
    orderNumber: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
};
export type Invoice = {
    id: Generated<string>;
    invoiceNumber: string | null;
    type: string;
    category: string;
    status: Generated<string>;
    invoiceDate: Timestamp | null;
    dueDate: Timestamp | null;
    billingPeriod: string | null;
    partyId: string | null;
    customerId: string | null;
    subtotal: number | null;
    gstRate: number | null;
    gstAmount: number | null;
    gstType: string | null;
    cgstAmount: number | null;
    sgstAmount: number | null;
    igstAmount: number | null;
    tdsRate: number | null;
    tdsSection: string | null;
    tdsAmount: Generated<number | null>;
    totalAmount: number;
    paidAmount: Generated<number>;
    balanceDue: Generated<number>;
    orderId: string | null;
    fileData: Buffer | null;
    filePath: string | null;
    fileName: string | null;
    fileMimeType: string | null;
    fileSizeBytes: number | null;
    fileHash: string | null;
    aiRawResponse: unknown | null;
    aiModel: string | null;
    aiConfidence: number | null;
    driveFileId: string | null;
    driveUrl: string | null;
    driveUploadedAt: Timestamp | null;
    ledgerEntryId: string | null;
    notes: string | null;
    settlementBatchRef: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type InvoiceLine = {
    id: Generated<string>;
    invoiceId: string;
    description: string | null;
    hsnCode: string | null;
    qty: number | null;
    unit: string | null;
    rate: number | null;
    amount: number | null;
    gstPercent: number | null;
    gstAmount: number | null;
    orderLineId: string | null;
    fabricColourId: string | null;
    matchedTxnId: string | null;
    matchType: string | null;
};
export type InvoiceSequence = {
    id: Generated<string>;
    prefix: string;
    currentNumber: Generated<number>;
    fiscalYear: string;
};
export type LeaveRecord = {
    id: Generated<string>;
    employeeId: string;
    date: Timestamp;
    type: string;
    reason: string | null;
    source: Generated<string>;
    createdById: string;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type LedgerAccount = {
    id: Generated<string>;
    code: string;
    name: string;
    type: string;
    balance: Generated<number>;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type LedgerEntry = {
    id: Generated<string>;
    entryDate: Timestamp;
    period: string;
    description: string;
    sourceType: string;
    sourceId: string | null;
    isReversed: Generated<boolean>;
    reversedById: string | null;
    notes: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type LedgerEntryLine = {
    id: Generated<string>;
    entryId: string;
    accountId: string;
    debit: Generated<number>;
    credit: Generated<number>;
    description: string | null;
};
export type MarketplacePayoutReport = {
    id: Generated<string>;
    marketplace: string;
    fileName: string;
    fileHash: string;
    reportPeriod: string;
    grossRevenue: Generated<number>;
    totalCommission: Generated<number>;
    bannerDeduction: Generated<number>;
    shippingCharges: Generated<number>;
    returnCharges: Generated<number>;
    tdsAmount: Generated<number>;
    otherIncome: Generated<number>;
    netPayout: Generated<number>;
    orderCount: Generated<number>;
    deliveredCount: Generated<number>;
    returnCount: Generated<number>;
    cancelledCount: Generated<number>;
    orderLines: unknown | null;
    matchedOrders: unknown | null;
    bankMatchResult: unknown | null;
    revenueInvoiceId: string | null;
    commissionInvoiceId: string | null;
    promoInvoiceId: string | null;
    bankTransactionId: string | null;
    status: Generated<string>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type Material = {
    id: Generated<string>;
    name: string;
    description: string | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type MonthlyStockSnapshot = {
    id: Generated<string>;
    skuId: string;
    month: Timestamp;
    openingStock: number;
    totalInward: number;
    totalOutward: number;
    closingStock: number;
    inwardBreakdown: Generated<unknown>;
    outwardBreakdown: Generated<unknown>;
    computedAt: Generated<Timestamp>;
};
export type Order = {
    id: Generated<string>;
    orderNumber: string;
    shopifyOrderId: string | null;
    channel: Generated<string>;
    customerId: string | null;
    customerName: string;
    customerEmail: string | null;
    customerPhone: string | null;
    shippingAddress: string | null;
    orderDate: Generated<Timestamp>;
    internalNotes: string | null;
    paymentMethod: string | null;
    status: Generated<string>;
    isArchived: Generated<boolean>;
    archivedAt: Timestamp | null;
    releasedToShipped: Generated<boolean>;
    releasedToCancelled: Generated<boolean>;
    totalAmount: number;
    createdAt: Generated<Timestamp>;
    syncedAt: Timestamp | null;
    codRemittanceUtr: string | null;
    codRemittedAmount: number | null;
    codRemittedAt: Timestamp | null;
    codShopifySyncError: string | null;
    codShopifySyncStatus: string | null;
    codShopifySyncedAt: Timestamp | null;
    settledAt: Timestamp | null;
    settlementAmount: number | null;
    settlementRef: string | null;
    paymentGateway: string | null;
    isExchange: Generated<boolean>;
    originalOrderId: string | null;
    shipByDate: Timestamp | null;
    sheetPushedAt: Timestamp | null;
    customerState: string | null;
    partiallyCancelled: Generated<boolean>;
    paymentConfirmedAt: Timestamp | null;
    paymentConfirmedBy: string | null;
    paymentStatus: Generated<string | null>;
    channelOrderId: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmTerm: string | null;
    fbclid: string | null;
    gclid: string | null;
    landingPage: string | null;
};
export type OrderLine = {
    id: Generated<string>;
    orderId: string;
    shopifyLineId: string | null;
    skuId: string;
    qty: number;
    unitPrice: number;
    lineStatus: Generated<string>;
    allocatedAt: Timestamp | null;
    pickedAt: Timestamp | null;
    packedAt: Timestamp | null;
    shippedAt: Timestamp | null;
    deliveredAt: Timestamp | null;
    inventoryTxnId: string | null;
    productionBatchId: string | null;
    notes: string | null;
    awbNumber: string | null;
    courier: string | null;
    trackingStatus: string | null;
    lastTrackingUpdate: Timestamp | null;
    lastScanAt: Timestamp | null;
    lastScanLocation: string | null;
    lastScanStatus: string | null;
    courierStatusCode: string | null;
    deliveryAttempts: number | null;
    expectedDeliveryDate: Timestamp | null;
    rtoInitiatedAt: Timestamp | null;
    rtoReceivedAt: Timestamp | null;
    rtoCondition: string | null;
    rtoInwardedAt: Timestamp | null;
    rtoInwardedById: string | null;
    rtoNotes: string | null;
    customizedAt: Timestamp | null;
    customizedById: string | null;
    isCustomized: Generated<boolean>;
    isNonReturnable: Generated<boolean>;
    originalSkuId: string | null;
    refundAmount: number | null;
    refundNotes: string | null;
    refundReason: string | null;
    refundedAt: Timestamp | null;
    shippingAddress: string | null;
    channelFulfillmentStatus: string | null;
    channelItemId: string | null;
    returnBatchNumber: string | null;
    returnStatus: string | null;
    returnQty: number | null;
    returnRequestedAt: Timestamp | null;
    returnRequestedById: string | null;
    returnPickupType: string | null;
    returnAwbNumber: string | null;
    returnCourier: string | null;
    returnPickupScheduledAt: Timestamp | null;
    returnPickupAt: Timestamp | null;
    returnReceivedAt: Timestamp | null;
    returnReceivedById: string | null;
    returnCondition: string | null;
    returnConditionNotes: string | null;
    returnQcResult: string | null;
    returnReasonCategory: string | null;
    returnReasonDetail: string | null;
    returnResolution: string | null;
    returnGrossAmount: string | null;
    returnDiscountClawback: string | null;
    returnDeductions: string | null;
    returnDeductionNotes: string | null;
    returnNetAmount: string | null;
    returnRefundRequestedMode: string | null;
    returnRefundLinkSentAt: Timestamp | null;
    returnRefundLinkId: string | null;
    returnRefundLinkUrl: string | null;
    returnRefundCompletedAt: Timestamp | null;
    returnRefundMethod: string | null;
    returnRefundReference: string | null;
    returnShippingFee: string | null;
    returnExchangeOrderId: string | null;
    returnExchangeSkuId: string | null;
    returnExchangePriceDiff: string | null;
    returnClosedManually: boolean | null;
    returnClosedManuallyAt: Timestamp | null;
    returnClosedManuallyById: string | null;
    returnClosedReason: string | null;
    returnNotes: string | null;
    returnPrimeRequestId: string | null;
    returnPrimeRequestNumber: string | null;
    returnPrimeStatus: string | null;
    returnPrimeCreatedAt: Timestamp | null;
    returnPrimeUpdatedAt: Timestamp | null;
    returnPrimeSyncedAt: Timestamp | null;
    returnPrimeSyncError: string | null;
    returnPrimeExchangeShopifyOrderId: string | null;
};
export type OrderPayment = {
    id: Generated<string>;
    orderId: string;
    amount: number;
    paymentMethod: string | null;
    reference: string | null;
    notes: string | null;
    recordedById: string;
    recordedAt: Generated<Timestamp>;
    createdAt: Generated<Timestamp>;
};
export type Party = {
    id: Generated<string>;
    name: string;
    category: string;
    contactName: string | null;
    email: string | null;
    phone: string | null;
    address: string | null;
    gstin: string | null;
    pan: string | null;
    stateCode: string | null;
    tdsApplicable: Generated<boolean>;
    tdsSection: string | null;
    tdsRate: number | null;
    bankAccountName: string | null;
    bankAccountNumber: string | null;
    bankIfsc: string | null;
    bankName: string | null;
    razorpayContactId: string | null;
    paymentTermsDays: number | null;
    billingPeriodOffsetMonths: number | null;
    aliases: Generated<string[]>;
    invoiceRequired: Generated<boolean>;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
    transactionTypeId: string | null;
};
export type PartyChangeLog = {
    id: Generated<string>;
    partyId: string;
    fieldName: string;
    oldValue: string | null;
    newValue: string | null;
    changedById: string;
    createdAt: Generated<Timestamp>;
};
export type Payment = {
    id: Generated<string>;
    referenceNumber: string | null;
    direction: string;
    method: string;
    status: Generated<string>;
    amount: number;
    matchedAmount: Generated<number>;
    unmatchedAmount: Generated<number>;
    paymentDate: Timestamp;
    partyId: string | null;
    customerId: string | null;
    fileData: Buffer | null;
    filePath: string | null;
    fileName: string | null;
    fileMimeType: string | null;
    fileSizeBytes: number | null;
    driveFileId: string | null;
    driveUrl: string | null;
    driveUploadedAt: Timestamp | null;
    ledgerEntryId: string | null;
    debitAccountCode: string | null;
    period: string | null;
    notes: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type PayrollRun = {
    id: Generated<string>;
    month: number;
    year: number;
    status: Generated<string>;
    /**
     * Totals (computed from slips)
     */
    totalGross: Generated<number>;
    totalDeductions: Generated<number>;
    totalNetPay: Generated<number>;
    totalEmployerCost: Generated<number>;
    employeeCount: Generated<number>;
    confirmedAt: Timestamp | null;
    confirmedById: string | null;
    notes: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type PayrollSlip = {
    id: Generated<string>;
    payrollRunId: string;
    employeeId: string;
    /**
     * Days
     */
    daysInMonth: number;
    payableDays: number;
    isManualDays: Generated<boolean>;
    /**
     * Fixed components (from salary structure at time of run)
     */
    basicFixed: number;
    hraFixed: number;
    otherAllowanceFixed: number;
    grossFixed: number;
    /**
     * Earned (pro-rated by payable days)
     */
    basicEarned: number;
    hraEarned: number;
    otherAllowanceEarned: number;
    grossEarned: number;
    /**
     * Employee deductions
     */
    pfEmployee: Generated<number>;
    esicEmployee: Generated<number>;
    professionalTax: Generated<number>;
    advances: Generated<number>;
    otherDeductions: Generated<number>;
    totalDeductions: Generated<number>;
    /**
     * Net pay
     */
    netPay: Generated<number>;
    /**
     * Employer contributions
     */
    pfEmployer: Generated<number>;
    pfAdmin: Generated<number>;
    esicEmployer: Generated<number>;
    totalEmployerCost: Generated<number>;
    costToCompany: Generated<number>;
    /**
     * Finance link
     */
    invoiceId: string | null;
    /**
     * External payroll system data (full register row from RazorpayPayroll etc.)
     */
    registerData: unknown | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type PayuSettlement = {
    id: Generated<string>;
    settlementId: string;
    utrNumber: string;
    settlementAmount: number;
    merchantId: string;
    settlementCompletedDate: Timestamp;
    transactions: unknown | null;
    transactionCount: Generated<number>;
    syncedAt: Generated<Timestamp>;
    bankTransactionId: string | null;
    matchedAt: Timestamp | null;
    matchConfidence: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type Pincode = {
    id: Generated<string>;
    pincode: string;
    district: string;
    state: string;
    region: string | null;
    division: string | null;
    createdAt: Generated<Timestamp>;
};
export type Product = {
    id: Generated<string>;
    name: string;
    styleCode: string | null;
    category: string;
    garmentGroup: Generated<string>;
    productType: string;
    gender: Generated<string>;
    googleProductCategoryId: number | null;
    attributes: unknown | null;
    baseProductionTimeMins: Generated<number>;
    defaultFabricConsumption: number | null;
    description: string | null;
    erpDescription: string | null;
    erpDescriptionHistory: unknown | null;
    erpSeoTitle: string | null;
    erpSeoDescription: string | null;
    imageUrl: string | null;
    notes: unknown | null;
    status: Generated<string>;
    isActive: Generated<boolean>;
    isReturnable: Generated<boolean>;
    nonReturnableReason: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
    shopifyProductId: string | null;
    shopifyHandle: string | null;
    exchangeCount: Generated<number>;
    returnCount: Generated<number>;
    writeOffCount: Generated<number>;
    hsnCode: string | null;
    shopifyProductIds: Generated<string[]>;
};
export type ProductBomTemplate = {
    id: Generated<string>;
    productId: string;
    roleId: string;
    trimItemId: string | null;
    serviceItemId: string | null;
    defaultQuantity: Generated<number>;
    quantityUnit: Generated<string>;
    wastagePercent: Generated<number>;
    notes: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ProductionBatch = {
    id: Generated<string>;
    batchCode: string | null;
    batchDate: Generated<Timestamp>;
    tailorId: string | null;
    skuId: string | null;
    sampleCode: string | null;
    sampleName: string | null;
    sampleColour: string | null;
    sampleSize: string | null;
    qtyPlanned: number;
    qtyCompleted: Generated<number>;
    priority: string;
    sourceOrderLineId: string | null;
    status: Generated<string>;
    notes: string | null;
    createdAt: Generated<Timestamp>;
    completedAt: Timestamp | null;
};
export type RepackingQueueItem = {
    id: Generated<string>;
    skuId: string;
    qty: Generated<number>;
    status: Generated<string>;
    condition: string;
    inspectionNotes: string | null;
    writeOffReason: string | null;
    createdAt: Generated<Timestamp>;
    processedAt: Timestamp | null;
    processedById: string | null;
    qcComments: string | null;
    orderLineId: string | null;
};
export type ReturnPrimeCsvEnrichment = {
    id: Generated<string>;
    requestNumber: string;
    requestType: string | null;
    status: string | null;
    csvReason: string | null;
    customerComment: string | null;
    inspectionNotes: string | null;
    notes: string | null;
    refundStatus: string | null;
    requestedRefundMode: string | null;
    actualRefundMode: string | null;
    refundedAtRaw: string | null;
    pickupAwb: string | null;
    pickupLogistics: string | null;
    sourceFile: string | null;
    rawRow: unknown | null;
    importedAt: Generated<Timestamp>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ReturnPrimeRequest = {
    id: Generated<string>;
    rpRequestId: string;
    rpRequestNumber: string;
    requestType: string;
    shopifyOrderId: string | null;
    shopifyOrderName: string | null;
    orderId: string | null;
    customerName: string | null;
    customerEmail: string | null;
    customerPhone: string | null;
    customerAddress: unknown | null;
    customerBank: unknown | null;
    isApproved: Generated<boolean>;
    approvedAt: Timestamp | null;
    approvedComment: string | null;
    isReceived: Generated<boolean>;
    receivedAt: Timestamp | null;
    receivedComment: string | null;
    isInspected: Generated<boolean>;
    inspectedAt: Timestamp | null;
    inspectedComment: string | null;
    isRefunded: Generated<boolean>;
    refundedAt: Timestamp | null;
    isRejected: Generated<boolean>;
    rejectedAt: Timestamp | null;
    rejectedComment: string | null;
    isArchived: Generated<boolean>;
    archivedAt: Timestamp | null;
    lineItems: Generated<unknown>;
    lineItemCount: Generated<number>;
    totalValue: Generated<string>;
    primaryReason: string | null;
    rpCreatedAt: Timestamp;
    rpUpdatedAt: Timestamp | null;
    syncedAt: Generated<Timestamp>;
    rawData: unknown | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ReturnSettings = {
    id: Generated<string>;
    /**
     * Days from delivery within which returns are accepted
     */
    windowDays: Generated<number>;
    /**
     * Days before window expiry to show warning (e.g., 12 means 2 days left warning)
     */
    windowWarningDays: Generated<number>;
    /**
     * Auto-reject returns after this many days (null = allow with override)
     */
    autoRejectAfterDays: number | null;
    /**
     * Allow returns after window expires with manual override
     */
    allowExpiredOverride: Generated<boolean>;
    /**
     * Return shipping fee (flat amount in INR, deducted from refund)
     */
    returnShippingFee: string | null;
    /**
     * Restocking fee type: 'flat' or 'percent'
     */
    restockingFeeType: string | null;
    /**
     * Restocking fee value (flat INR amount or percentage 0-100)
     */
    restockingFeeValue: string | null;
    updatedAt: Timestamp;
    updatedById: string | null;
};
export type Role = {
    id: Generated<string>;
    name: string;
    displayName: string;
    description: string | null;
    permissions: unknown;
    isBuiltIn: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type SalaryRevision = {
    id: Generated<string>;
    employeeId: string;
    basicSalary: number;
    pfApplicable: boolean;
    esicApplicable: boolean;
    ptApplicable: boolean;
    effectiveFrom: Timestamp;
    reason: string | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
};
export type ServiceItem = {
    id: Generated<string>;
    code: string;
    name: string;
    category: string;
    description: string | null;
    costPerJob: number;
    costUnit: Generated<string>;
    partyId: string | null;
    leadTimeDays: number | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type ShopifyInventoryCache = {
    skuId: string;
    shopifyInventoryItemId: string;
    availableQty: number;
    lastSynced: Generated<Timestamp>;
};
export type ShopifyOrderCache = {
    id: string;
    rawData: string;
    orderNumber: string | null;
    financialStatus: string | null;
    fulfillmentStatus: string | null;
    lastWebhookAt: Generated<Timestamp>;
    webhookTopic: string | null;
    processedAt: Timestamp | null;
    processingError: string | null;
    createdAt: Generated<Timestamp>;
    customerNotes: string | null;
    discountCodes: string | null;
    paymentMethod: string | null;
    shippedAt: Timestamp | null;
    shippingCity: string | null;
    shippingCountry: string | null;
    shippingState: string | null;
    tags: string | null;
    trackingCompany: string | null;
    trackingNumber: string | null;
    trackingUrl: string | null;
    deliveredAt: Timestamp | null;
    fulfillmentUpdatedAt: Timestamp | null;
    shipmentStatus: string | null;
    processingLock: Timestamp | null;
    billingCity: string | null;
    billingName: string | null;
    billingPhone: string | null;
    billingState: string | null;
    billingZip: string | null;
    buyerAcceptsMarketing: boolean | null;
    cancelReason: string | null;
    confirmationNumber: string | null;
    currency: string | null;
    customerEmail: string | null;
    customerFirstName: string | null;
    customerId: string | null;
    customerLastName: string | null;
    customerPhone: string | null;
    fulfillmentCount: number | null;
    isConfirmed: boolean | null;
    isTaxExempt: boolean | null;
    isTest: boolean | null;
    lineItemCount: number | null;
    paymentGatewayNames: string | null;
    refundCount: number | null;
    shippingAddress1: string | null;
    shippingAddress2: string | null;
    shippingCountryCode: string | null;
    shippingLatitude: number | null;
    shippingLongitude: number | null;
    shippingName: string | null;
    shippingPhone: string | null;
    shippingProvince: string | null;
    shippingProvinceCode: string | null;
    shippingZip: string | null;
    shopifyCancelledAt: Timestamp | null;
    shopifyClosedAt: Timestamp | null;
    shopifyCreatedAt: Timestamp | null;
    shopifyOrderName: string | null;
    shopifyProcessedAt: Timestamp | null;
    shopifyUpdatedAt: Timestamp | null;
    sourceName: string | null;
    totalLineItemsPrice: number | null;
    totalOutstanding: number | null;
    totalShippingPrice: number | null;
    totalPrice: string | null;
    subtotalPrice: string | null;
    totalTax: string | null;
    totalDiscounts: string | null;
    lineItemsJson: string | null;
    shippingLinesJson: string | null;
    taxLinesJson: string | null;
    noteAttributesJson: string | null;
    billingAddress1: string | null;
    billingAddress2: string | null;
    billingCountry: string | null;
    billingCountryCode: string | null;
};
export type ShopifyProductCache = {
    id: string;
    rawData: string;
    title: string | null;
    handle: string | null;
    lastWebhookAt: Generated<Timestamp>;
    webhookTopic: string | null;
    processedAt: Timestamp | null;
    processingError: string | null;
    createdAt: Generated<Timestamp>;
};
export type Sku = {
    id: Generated<string>;
    skuCode: string;
    variationId: string;
    size: string;
    mrp: number;
    sellingPrice: number | null;
    currentBalance: Generated<number>;
    targetStockQty: Generated<number>;
    targetStockMethod: Generated<string>;
    isActive: Generated<boolean>;
    shopifyInventoryItemId: string | null;
    shopifyVariantId: string | null;
    exchangeCount: Generated<number>;
    returnCount: Generated<number>;
    writeOffCount: Generated<number>;
    customizationCount: Generated<number>;
    customizationNotes: string | null;
    customizationType: string | null;
    customizationValue: string | null;
    isCustomSku: Generated<boolean>;
    linkedOrderLineId: string | null;
    parentSkuId: string | null;
    bomCost: number | null;
};
export type SkuBomLine = {
    id: Generated<string>;
    skuId: string;
    roleId: string;
    fabricColourId: string | null;
    trimItemId: string | null;
    serviceItemId: string | null;
    quantity: number | null;
    wastagePercent: number | null;
    overrideCost: number | null;
    notes: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type StorefrontEvent = {
    id: Generated<string>;
    eventName: string;
    eventTime: Timestamp;
    createdAt: Generated<Timestamp>;
    sessionId: string;
    visitorId: string;
    pageUrl: string | null;
    referrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
    productId: string | null;
    productTitle: string | null;
    variantId: string | null;
    variantTitle: string | null;
    collectionId: string | null;
    collectionTitle: string | null;
    searchQuery: string | null;
    cartValue: number | null;
    orderValue: number | null;
    userAgent: string | null;
    screenWidth: number | null;
    screenHeight: number | null;
    deviceType: string | null;
    country: string | null;
    region: string | null;
    rawData: unknown | null;
};
export type StyleMeasurement = {
    id: Generated<string>;
    styleCode: string;
    unit: Generated<string>;
    measurements: Generated<unknown>;
    fitComments: Generated<unknown>;
    sampleSize: string | null;
    isFullyGraded: Generated<boolean>;
    /**
     * UK/US/EU equivalents per size, e.g. { "M": { "uk": 10, "us": 6, "eu": 38 } }
     */
    sizeEquivalents: unknown | null;
    source: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type SyncJob = {
    id: Generated<string>;
    jobType: string;
    status: Generated<string>;
    dateFilter: string | null;
    daysBack: number | null;
    syncMode: string | null;
    staleAfterMins: number | null;
    totalRecords: number | null;
    processed: Generated<number>;
    created: Generated<number>;
    updated: Generated<number>;
    skipped: Generated<number>;
    errors: Generated<number>;
    lastProcessedId: string | null;
    currentBatch: Generated<number>;
    errorLog: string | null;
    lastError: string | null;
    startedAt: Timestamp | null;
    completedAt: Timestamp | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type SystemSetting = {
    key: string;
    value: string;
    updatedAt: Timestamp;
};
export type Tailor = {
    id: Generated<string>;
    name: string;
    specializations: string | null;
    dailyCapacityMins: Generated<number>;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
};
export type TrackingApiResponse = {
    id: Generated<string>;
    awbNumber: string;
    source: string;
    statusCode: number;
    response: unknown;
    createdAt: Generated<Timestamp>;
};
export type TransactionType = {
    id: Generated<string>;
    name: string;
    description: string | null;
    debitAccountCode: string | null;
    creditAccountCode: string | null;
    defaultGstRate: number | null;
    defaultTdsApplicable: Generated<boolean>;
    defaultTdsSection: string | null;
    defaultTdsRate: number | null;
    invoiceRequired: Generated<boolean>;
    expenseCategory: string | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type TransactionTypeChangeLog = {
    id: Generated<string>;
    transactionTypeId: string;
    fieldName: string;
    oldValue: string | null;
    newValue: string | null;
    changedById: string;
    createdAt: Generated<Timestamp>;
};
export type TrimItem = {
    id: Generated<string>;
    code: string;
    name: string;
    category: string;
    description: string | null;
    costPerUnit: number;
    unit: Generated<string>;
    partyId: string | null;
    minOrderQty: number | null;
    leadTimeDays: number | null;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type User = {
    id: Generated<string>;
    email: string;
    phone: string | null;
    password: string;
    name: string;
    role: Generated<string>;
    isActive: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
    mustChangePassword: Generated<boolean>;
    roleId: string | null;
    tokenVersion: Generated<number>;
    extraAccess: Generated<unknown>;
};
export type UserGridPreference = {
    id: Generated<string>;
    userId: string;
    gridId: string;
    visibleColumns: string;
    columnOrder: string;
    columnWidths: string;
    adminVersion: Timestamp | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type UserPermissionOverride = {
    id: Generated<string>;
    userId: string;
    permission: string;
    granted: boolean;
    createdAt: Generated<Timestamp>;
};
export type Variation = {
    id: Generated<string>;
    productId: string;
    colorName: string;
    standardColor: string | null;
    colorHex: string | null;
    imageUrl: string | null;
    isActive: Generated<boolean>;
    hasLining: Generated<boolean>;
    bomCost: number | null;
    shopifySourceProductId: string | null;
    shopifySourceHandle: string | null;
};
export type VariationBomLine = {
    id: Generated<string>;
    variationId: string;
    roleId: string;
    fabricColourId: string | null;
    trimItemId: string | null;
    serviceItemId: string | null;
    quantity: number | null;
    wastagePercent: number | null;
    notes: string | null;
    createdAt: Generated<Timestamp>;
    updatedAt: Timestamp;
};
export type WebhookLog = {
    id: Generated<string>;
    webhookId: string;
    topic: string;
    resourceId: string | null;
    source: Generated<string>;
    status: Generated<string>;
    responseCode: number | null;
    processingTime: number | null;
    error: string | null;
    payload: string | null;
    resultData: string | null;
    receivedAt: Generated<Timestamp>;
    processedAt: Timestamp | null;
};
export type WorkerRun = {
    id: Generated<string>;
    workerName: string;
    status: Generated<string>;
    startedAt: Timestamp;
    completedAt: Timestamp | null;
    durationMs: number | null;
    result: unknown | null;
    error: string | null;
    triggeredBy: Generated<string>;
    createdAt: Generated<Timestamp>;
};
export type WriteOffLog = {
    id: Generated<string>;
    skuId: string;
    qty: number;
    reason: string;
    sourceType: string;
    sourceId: string | null;
    notes: string | null;
    costValue: number | null;
    createdById: string;
    createdAt: Generated<Timestamp>;
};
export type DB = {
    Allocation: Allocation;
    AttendanceRecord: AttendanceRecord;
    Audience: Audience;
    BankImportBatch: BankImportBatch;
    BankTransaction: BankTransaction;
    ChannelImportBatch: ChannelImportBatch;
    ChannelOrderLine: ChannelOrderLine;
    CodRemittance: CodRemittance;
    ComponentRole: ComponentRole;
    ComponentType: ComponentType;
    CostConfig: CostConfig;
    Customer: Customer;
    DemandForecast: DemandForecast;
    DomainEvent: DomainEvent;
    EmailCampaign: EmailCampaign;
    EmailCampaignRecipient: EmailCampaignRecipient;
    EmailLog: EmailLog;
    Employee: Employee;
    Fabric: Fabric;
    FabricColour: FabricColour;
    FabricColourReconciliation: FabricColourReconciliation;
    FabricColourReconciliationItem: FabricColourReconciliationItem;
    FabricColourTransaction: FabricColourTransaction;
    FabricOrder: FabricOrder;
    FabricReconciliation: FabricReconciliation;
    FabricReconciliationItem: FabricReconciliationItem;
    FabricStockCount: FabricStockCount;
    FailedSyncItem: FailedSyncItem;
    Feedback: Feedback;
    FeedbackContent: FeedbackContent;
    FeedbackMedia: FeedbackMedia;
    FeedbackProductLink: FeedbackProductLink;
    FeedbackRating: FeedbackRating;
    FeedbackTag: FeedbackTag;
    InventoryReconciliation: InventoryReconciliation;
    InventoryReconciliationItem: InventoryReconciliationItem;
    InventoryTransaction: InventoryTransaction;
    Invoice: Invoice;
    InvoiceLine: InvoiceLine;
    InvoiceSequence: InvoiceSequence;
    LeaveRecord: LeaveRecord;
    LedgerAccount: LedgerAccount;
    LedgerEntry: LedgerEntry;
    LedgerEntryLine: LedgerEntryLine;
    MarketplacePayoutReport: MarketplacePayoutReport;
    Material: Material;
    MonthlyStockSnapshot: MonthlyStockSnapshot;
    Order: Order;
    OrderLine: OrderLine;
    OrderPayment: OrderPayment;
    Party: Party;
    PartyChangeLog: PartyChangeLog;
    Payment: Payment;
    PayrollRun: PayrollRun;
    PayrollSlip: PayrollSlip;
    PayuSettlement: PayuSettlement;
    Pincode: Pincode;
    Product: Product;
    ProductBomTemplate: ProductBomTemplate;
    ProductionBatch: ProductionBatch;
    RepackingQueueItem: RepackingQueueItem;
    ReturnPrimeCsvEnrichment: ReturnPrimeCsvEnrichment;
    ReturnPrimeRequest: ReturnPrimeRequest;
    ReturnSettings: ReturnSettings;
    Role: Role;
    SalaryRevision: SalaryRevision;
    ServiceItem: ServiceItem;
    ShopifyInventoryCache: ShopifyInventoryCache;
    ShopifyOrderCache: ShopifyOrderCache;
    ShopifyProductCache: ShopifyProductCache;
    Sku: Sku;
    SkuBomLine: SkuBomLine;
    StorefrontEvent: StorefrontEvent;
    StyleMeasurement: StyleMeasurement;
    SyncJob: SyncJob;
    SystemSetting: SystemSetting;
    Tailor: Tailor;
    TrackingApiResponse: TrackingApiResponse;
    TransactionType: TransactionType;
    TransactionTypeChangeLog: TransactionTypeChangeLog;
    TrimItem: TrimItem;
    User: User;
    UserGridPreference: UserGridPreference;
    UserPermissionOverride: UserPermissionOverride;
    Variation: Variation;
    VariationBomLine: VariationBomLine;
    WebhookLog: WebhookLog;
    WorkerRun: WorkerRun;
    WriteOffLog: WriteOffLog;
};
