/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as ReturnInwardRouteImport } from './routes/return-inward'
import { Route as ProductionInwardRouteImport } from './routes/production-inward'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InwardHubRouteImport } from './routes/inward-hub'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReturnsRtoRouteImport } from './routes/_authenticated/returns-rto'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedOrderSearchRouteImport } from './routes/_authenticated/order-search'
import { Route as AuthenticatedLedgersRouteImport } from './routes/_authenticated/ledgers'
import { Route as AuthenticatedInventoryInwardRouteImport } from './routes/_authenticated/inventory-inward'
import { Route as AuthenticatedInventoryCountRouteImport } from './routes/_authenticated/inventory-count'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFabricsRouteImport } from './routes/_authenticated/fabrics'
import { Route as AuthenticatedFabricReconciliationRouteImport } from './routes/_authenticated/fabric-reconciliation'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'

const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnInwardRoute = ReturnInwardRouteImport.update({
  id: '/return-inward',
  path: '/return-inward',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionInwardRoute = ProductionInwardRouteImport.update({
  id: '/production-inward',
  path: '/production-inward',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InwardHubRoute = InwardHubRouteImport.update({
  id: '/inward-hub',
  path: '/inward-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReturnsRtoRoute = AuthenticatedReturnsRtoRouteImport.update({
  id: '/returns-rto',
  path: '/returns-rto',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrderSearchRoute =
  AuthenticatedOrderSearchRouteImport.update({
    id: '/order-search',
    path: '/order-search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLedgersRoute = AuthenticatedLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryInwardRoute =
  AuthenticatedInventoryInwardRouteImport.update({
    id: '/inventory-inward',
    path: '/inventory-inward',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryCountRoute =
  AuthenticatedInventoryCountRouteImport.update({
    id: '/inventory-count',
    path: '/inventory-count',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFabricsRoute = AuthenticatedFabricsRouteImport.update({
  id: '/fabrics',
  path: '/fabrics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFabricReconciliationRoute =
  AuthenticatedFabricReconciliationRouteImport.update({
    id: '/fabric-reconciliation',
    path: '/fabric-reconciliation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/catalog': typeof CatalogRoute
  '/inward-hub': typeof InwardHubRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/production-inward': typeof ProductionInwardRoute
  '/return-inward': typeof ReturnInwardRoute
  '/shipments': typeof ShipmentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/fabric-reconciliation': typeof AuthenticatedFabricReconciliationRoute
  '/fabrics': typeof AuthenticatedFabricsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/inventory-count': typeof AuthenticatedInventoryCountRoute
  '/inventory-inward': typeof AuthenticatedInventoryInwardRoute
  '/ledgers': typeof AuthenticatedLedgersRoute
  '/order-search': typeof AuthenticatedOrderSearchRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/returns-rto': typeof AuthenticatedReturnsRtoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/catalog': typeof CatalogRoute
  '/inward-hub': typeof InwardHubRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/production-inward': typeof ProductionInwardRoute
  '/return-inward': typeof ReturnInwardRoute
  '/shipments': typeof ShipmentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/fabric-reconciliation': typeof AuthenticatedFabricReconciliationRoute
  '/fabrics': typeof AuthenticatedFabricsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/inventory-count': typeof AuthenticatedInventoryCountRoute
  '/inventory-inward': typeof AuthenticatedInventoryInwardRoute
  '/ledgers': typeof AuthenticatedLedgersRoute
  '/order-search': typeof AuthenticatedOrderSearchRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/returns-rto': typeof AuthenticatedReturnsRtoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/inward-hub': typeof InwardHubRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/production-inward': typeof ProductionInwardRoute
  '/return-inward': typeof ReturnInwardRoute
  '/shipments': typeof ShipmentsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/fabric-reconciliation': typeof AuthenticatedFabricReconciliationRoute
  '/_authenticated/fabrics': typeof AuthenticatedFabricsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/inventory-count': typeof AuthenticatedInventoryCountRoute
  '/_authenticated/inventory-inward': typeof AuthenticatedInventoryInwardRoute
  '/_authenticated/ledgers': typeof AuthenticatedLedgersRoute
  '/_authenticated/order-search': typeof AuthenticatedOrderSearchRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/_authenticated/returns-rto': typeof AuthenticatedReturnsRtoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/inward-hub'
    | '/login'
    | '/materials'
    | '/production-inward'
    | '/return-inward'
    | '/shipments'
    | '/analytics'
    | '/customers'
    | '/fabric-reconciliation'
    | '/fabrics'
    | '/inventory'
    | '/inventory-count'
    | '/inventory-inward'
    | '/ledgers'
    | '/order-search'
    | '/orders'
    | '/production'
    | '/products'
    | '/returns'
    | '/returns-rto'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/catalog'
    | '/inward-hub'
    | '/login'
    | '/materials'
    | '/production-inward'
    | '/return-inward'
    | '/shipments'
    | '/analytics'
    | '/customers'
    | '/fabric-reconciliation'
    | '/fabrics'
    | '/inventory'
    | '/inventory-count'
    | '/inventory-inward'
    | '/ledgers'
    | '/order-search'
    | '/orders'
    | '/production'
    | '/products'
    | '/returns'
    | '/returns-rto'
    | '/settings'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/catalog'
    | '/inward-hub'
    | '/login'
    | '/materials'
    | '/production-inward'
    | '/return-inward'
    | '/shipments'
    | '/_authenticated/analytics'
    | '/_authenticated/customers'
    | '/_authenticated/fabric-reconciliation'
    | '/_authenticated/fabrics'
    | '/_authenticated/inventory'
    | '/_authenticated/inventory-count'
    | '/_authenticated/inventory-inward'
    | '/_authenticated/ledgers'
    | '/_authenticated/order-search'
    | '/_authenticated/orders'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/returns'
    | '/_authenticated/returns-rto'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  InwardHubRoute: typeof InwardHubRoute
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRoute
  ProductionInwardRoute: typeof ProductionInwardRoute
  ReturnInwardRoute: typeof ReturnInwardRoute
  ShipmentsRoute: typeof ShipmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-inward': {
      id: '/return-inward'
      path: '/return-inward'
      fullPath: '/return-inward'
      preLoaderRoute: typeof ReturnInwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-inward': {
      id: '/production-inward'
      path: '/production-inward'
      fullPath: '/production-inward'
      preLoaderRoute: typeof ProductionInwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inward-hub': {
      id: '/inward-hub'
      path: '/inward-hub'
      fullPath: '/inward-hub'
      preLoaderRoute: typeof InwardHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/returns-rto': {
      id: '/_authenticated/returns-rto'
      path: '/returns-rto'
      fullPath: '/returns-rto'
      preLoaderRoute: typeof AuthenticatedReturnsRtoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order-search': {
      id: '/_authenticated/order-search'
      path: '/order-search'
      fullPath: '/order-search'
      preLoaderRoute: typeof AuthenticatedOrderSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ledgers': {
      id: '/_authenticated/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof AuthenticatedLedgersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory-inward': {
      id: '/_authenticated/inventory-inward'
      path: '/inventory-inward'
      fullPath: '/inventory-inward'
      preLoaderRoute: typeof AuthenticatedInventoryInwardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory-count': {
      id: '/_authenticated/inventory-count'
      path: '/inventory-count'
      fullPath: '/inventory-count'
      preLoaderRoute: typeof AuthenticatedInventoryCountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fabrics': {
      id: '/_authenticated/fabrics'
      path: '/fabrics'
      fullPath: '/fabrics'
      preLoaderRoute: typeof AuthenticatedFabricsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fabric-reconciliation': {
      id: '/_authenticated/fabric-reconciliation'
      path: '/fabric-reconciliation'
      fullPath: '/fabric-reconciliation'
      preLoaderRoute: typeof AuthenticatedFabricReconciliationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedFabricReconciliationRoute: typeof AuthenticatedFabricReconciliationRoute
  AuthenticatedFabricsRoute: typeof AuthenticatedFabricsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInventoryCountRoute: typeof AuthenticatedInventoryCountRoute
  AuthenticatedInventoryInwardRoute: typeof AuthenticatedInventoryInwardRoute
  AuthenticatedLedgersRoute: typeof AuthenticatedLedgersRoute
  AuthenticatedOrderSearchRoute: typeof AuthenticatedOrderSearchRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedReturnsRtoRoute: typeof AuthenticatedReturnsRtoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedFabricReconciliationRoute:
    AuthenticatedFabricReconciliationRoute,
  AuthenticatedFabricsRoute: AuthenticatedFabricsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInventoryCountRoute: AuthenticatedInventoryCountRoute,
  AuthenticatedInventoryInwardRoute: AuthenticatedInventoryInwardRoute,
  AuthenticatedLedgersRoute: AuthenticatedLedgersRoute,
  AuthenticatedOrderSearchRoute: AuthenticatedOrderSearchRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedReturnsRtoRoute: AuthenticatedReturnsRtoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CatalogRoute: CatalogRoute,
  InwardHubRoute: InwardHubRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  ProductionInwardRoute: ProductionInwardRoute,
  ReturnInwardRoute: ReturnInwardRoute,
  ShipmentsRoute: ShipmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
