/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as ReturnInwardRouteImport } from './routes/return-inward'
import { Route as ProductionInwardRouteImport } from './routes/production-inward'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InwardHubRouteImport } from './routes/inward-hub'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated/tracking'
import { Route as AuthenticatedTailorPerformanceRouteImport } from './routes/_authenticated/tailor-performance'
import { Route as AuthenticatedStorefrontRouteImport } from './routes/_authenticated/storefront'
import { Route as AuthenticatedStockReportRouteImport } from './routes/_authenticated/stock-report'
import { Route as AuthenticatedShopifyCatalogRouteImport } from './routes/_authenticated/shopify-catalog'
import { Route as AuthenticatedSheetsMonitorRouteImport } from './routes/_authenticated/sheets-monitor'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReturnsRtoRouteImport } from './routes/_authenticated/returns-rto'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedReturnPrimeRouteImport } from './routes/_authenticated/return-prime'
import { Route as AuthenticatedQuickOrderRouteImport } from './routes/_authenticated/quick-order'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedOrderSearchRouteImport } from './routes/_authenticated/order-search'
import { Route as AuthenticatedLedgersRouteImport } from './routes/_authenticated/ledgers'
import { Route as AuthenticatedInventoryInwardRouteImport } from './routes/_authenticated/inventory-inward'
import { Route as AuthenticatedInventoryCountRouteImport } from './routes/_authenticated/inventory-count'
import { Route as AuthenticatedInventoryAdjustmentsRouteImport } from './routes/_authenticated/inventory-adjustments'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedGrowthAnalyticsRouteImport } from './routes/_authenticated/growth-analytics'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFacebookFeedHealthRouteImport } from './routes/_authenticated/facebook-feed-health'
import { Route as AuthenticatedFabricsRouteImport } from './routes/_authenticated/fabrics'
import { Route as AuthenticatedFabricCountRouteImport } from './routes/_authenticated/fabric-count'
import { Route as AuthenticatedDemandForecastRouteImport } from './routes/_authenticated/demand-forecast'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCostingRouteImport } from './routes/_authenticated/costing'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedChannelImportRouteImport } from './routes/_authenticated/channel-import'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedBomRouteImport } from './routes/_authenticated/bom'
import { Route as AuthenticatedAudiencesRouteImport } from './routes/_authenticated/audiences'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedBusinessIndexRouteImport } from './routes/_authenticated/business/index'
import { Route as AuthenticatedReturnsReturnIdRouteImport } from './routes/_authenticated/returns_.$returnId'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products_.new'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders_.$orderId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers_.$customerId'
import { Route as AuthenticatedCampaignsCampaignIdRouteImport } from './routes/_authenticated/campaigns_.$campaignId'
import { Route as AuthenticatedProductsProductSlugEditRouteImport } from './routes/_authenticated/products_/$productSlug/edit'

const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnInwardRoute = ReturnInwardRouteImport.update({
  id: '/return-inward',
  path: '/return-inward',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionInwardRoute = ProductionInwardRouteImport.update({
  id: '/production-inward',
  path: '/production-inward',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InwardHubRoute = InwardHubRouteImport.update({
  id: '/inward-hub',
  path: '/inward-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTailorPerformanceRoute =
  AuthenticatedTailorPerformanceRouteImport.update({
    id: '/tailor-performance',
    path: '/tailor-performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStorefrontRoute = AuthenticatedStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockReportRoute =
  AuthenticatedStockReportRouteImport.update({
    id: '/stock-report',
    path: '/stock-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShopifyCatalogRoute =
  AuthenticatedShopifyCatalogRouteImport.update({
    id: '/shopify-catalog',
    path: '/shopify-catalog',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSheetsMonitorRoute =
  AuthenticatedSheetsMonitorRouteImport.update({
    id: '/sheets-monitor',
    path: '/sheets-monitor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReturnsRtoRoute = AuthenticatedReturnsRtoRouteImport.update({
  id: '/returns-rto',
  path: '/returns-rto',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReturnPrimeRoute =
  AuthenticatedReturnPrimeRouteImport.update({
    id: '/return-prime',
    path: '/return-prime',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuickOrderRoute = AuthenticatedQuickOrderRouteImport.update({
  id: '/quick-order',
  path: '/quick-order',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrderSearchRoute =
  AuthenticatedOrderSearchRouteImport.update({
    id: '/order-search',
    path: '/order-search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLedgersRoute = AuthenticatedLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryInwardRoute =
  AuthenticatedInventoryInwardRouteImport.update({
    id: '/inventory-inward',
    path: '/inventory-inward',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryCountRoute =
  AuthenticatedInventoryCountRouteImport.update({
    id: '/inventory-count',
    path: '/inventory-count',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAdjustmentsRoute =
  AuthenticatedInventoryAdjustmentsRouteImport.update({
    id: '/inventory-adjustments',
    path: '/inventory-adjustments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrowthAnalyticsRoute =
  AuthenticatedGrowthAnalyticsRouteImport.update({
    id: '/growth-analytics',
    path: '/growth-analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacebookFeedHealthRoute =
  AuthenticatedFacebookFeedHealthRouteImport.update({
    id: '/facebook-feed-health',
    path: '/facebook-feed-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFabricsRoute = AuthenticatedFabricsRouteImport.update({
  id: '/fabrics',
  path: '/fabrics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFabricCountRoute =
  AuthenticatedFabricCountRouteImport.update({
    id: '/fabric-count',
    path: '/fabric-count',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemandForecastRoute =
  AuthenticatedDemandForecastRouteImport.update({
    id: '/demand-forecast',
    path: '/demand-forecast',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCostingRoute = AuthenticatedCostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelImportRoute =
  AuthenticatedChannelImportRouteImport.update({
    id: '/channel-import',
    path: '/channel-import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBomRoute = AuthenticatedBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAudiencesRoute = AuthenticatedAudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBusinessIndexRoute =
  AuthenticatedBusinessIndexRouteImport.update({
    id: '/business/',
    path: '/business/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReturnsReturnIdRoute =
  AuthenticatedReturnsReturnIdRouteImport.update({
    id: '/returns_/$returnId',
    path: '/returns/$returnId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products_/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders_/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers_/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdRoute =
  AuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns_/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductSlugEditRoute =
  AuthenticatedProductsProductSlugEditRouteImport.update({
    id: '/products_/$productSlug/edit',
    path: '/products/$productSlug/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/catalog': typeof CatalogRoute
  '/inward-hub': typeof InwardHubRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/production-inward': typeof ProductionInwardRoute
  '/return-inward': typeof ReturnInwardRoute
  '/shipments': typeof ShipmentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audiences': typeof AuthenticatedAudiencesRoute
  '/bom': typeof AuthenticatedBomRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/channel-import': typeof AuthenticatedChannelImportRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/costing': typeof AuthenticatedCostingRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/demand-forecast': typeof AuthenticatedDemandForecastRoute
  '/fabric-count': typeof AuthenticatedFabricCountRoute
  '/fabrics': typeof AuthenticatedFabricsRoute
  '/facebook-feed-health': typeof AuthenticatedFacebookFeedHealthRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/growth-analytics': typeof AuthenticatedGrowthAnalyticsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/inventory-adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/inventory-count': typeof AuthenticatedInventoryCountRoute
  '/inventory-inward': typeof AuthenticatedInventoryInwardRoute
  '/ledgers': typeof AuthenticatedLedgersRoute
  '/order-search': typeof AuthenticatedOrderSearchRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/quick-order': typeof AuthenticatedQuickOrderRoute
  '/return-prime': typeof AuthenticatedReturnPrimeRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/returns-rto': typeof AuthenticatedReturnsRtoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets-monitor': typeof AuthenticatedSheetsMonitorRoute
  '/shopify-catalog': typeof AuthenticatedShopifyCatalogRoute
  '/stock-report': typeof AuthenticatedStockReportRoute
  '/storefront': typeof AuthenticatedStorefrontRoute
  '/tailor-performance': typeof AuthenticatedTailorPerformanceRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/returns/$returnId': typeof AuthenticatedReturnsReturnIdRoute
  '/business/': typeof AuthenticatedBusinessIndexRoute
  '/products/$productSlug/edit': typeof AuthenticatedProductsProductSlugEditRoute
}
export interface FileRoutesByTo {
  '/catalog': typeof CatalogRoute
  '/inward-hub': typeof InwardHubRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/production-inward': typeof ProductionInwardRoute
  '/return-inward': typeof ReturnInwardRoute
  '/shipments': typeof ShipmentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audiences': typeof AuthenticatedAudiencesRoute
  '/bom': typeof AuthenticatedBomRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/channel-import': typeof AuthenticatedChannelImportRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/costing': typeof AuthenticatedCostingRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/demand-forecast': typeof AuthenticatedDemandForecastRoute
  '/fabric-count': typeof AuthenticatedFabricCountRoute
  '/fabrics': typeof AuthenticatedFabricsRoute
  '/facebook-feed-health': typeof AuthenticatedFacebookFeedHealthRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/growth-analytics': typeof AuthenticatedGrowthAnalyticsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/inventory-adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/inventory-count': typeof AuthenticatedInventoryCountRoute
  '/inventory-inward': typeof AuthenticatedInventoryInwardRoute
  '/ledgers': typeof AuthenticatedLedgersRoute
  '/order-search': typeof AuthenticatedOrderSearchRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/quick-order': typeof AuthenticatedQuickOrderRoute
  '/return-prime': typeof AuthenticatedReturnPrimeRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/returns-rto': typeof AuthenticatedReturnsRtoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets-monitor': typeof AuthenticatedSheetsMonitorRoute
  '/shopify-catalog': typeof AuthenticatedShopifyCatalogRoute
  '/stock-report': typeof AuthenticatedStockReportRoute
  '/storefront': typeof AuthenticatedStorefrontRoute
  '/tailor-performance': typeof AuthenticatedTailorPerformanceRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/returns/$returnId': typeof AuthenticatedReturnsReturnIdRoute
  '/business': typeof AuthenticatedBusinessIndexRoute
  '/products/$productSlug/edit': typeof AuthenticatedProductsProductSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/inward-hub': typeof InwardHubRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/production-inward': typeof ProductionInwardRoute
  '/return-inward': typeof ReturnInwardRoute
  '/shipments': typeof ShipmentsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audiences': typeof AuthenticatedAudiencesRoute
  '/_authenticated/bom': typeof AuthenticatedBomRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/channel-import': typeof AuthenticatedChannelImportRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/costing': typeof AuthenticatedCostingRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/demand-forecast': typeof AuthenticatedDemandForecastRoute
  '/_authenticated/fabric-count': typeof AuthenticatedFabricCountRoute
  '/_authenticated/fabrics': typeof AuthenticatedFabricsRoute
  '/_authenticated/facebook-feed-health': typeof AuthenticatedFacebookFeedHealthRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/growth-analytics': typeof AuthenticatedGrowthAnalyticsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/inventory-adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/_authenticated/inventory-count': typeof AuthenticatedInventoryCountRoute
  '/_authenticated/inventory-inward': typeof AuthenticatedInventoryInwardRoute
  '/_authenticated/ledgers': typeof AuthenticatedLedgersRoute
  '/_authenticated/order-search': typeof AuthenticatedOrderSearchRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/quick-order': typeof AuthenticatedQuickOrderRoute
  '/_authenticated/return-prime': typeof AuthenticatedReturnPrimeRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/_authenticated/returns-rto': typeof AuthenticatedReturnsRtoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sheets-monitor': typeof AuthenticatedSheetsMonitorRoute
  '/_authenticated/shopify-catalog': typeof AuthenticatedShopifyCatalogRoute
  '/_authenticated/stock-report': typeof AuthenticatedStockReportRoute
  '/_authenticated/storefront': typeof AuthenticatedStorefrontRoute
  '/_authenticated/tailor-performance': typeof AuthenticatedTailorPerformanceRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/campaigns_/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/_authenticated/customers_/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/orders_/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/products_/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/returns_/$returnId': typeof AuthenticatedReturnsReturnIdRoute
  '/_authenticated/business/': typeof AuthenticatedBusinessIndexRoute
  '/_authenticated/products_/$productSlug/edit': typeof AuthenticatedProductsProductSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/inward-hub'
    | '/login'
    | '/materials'
    | '/production-inward'
    | '/return-inward'
    | '/shipments'
    | '/analytics'
    | '/audiences'
    | '/bom'
    | '/campaigns'
    | '/channel-import'
    | '/channels'
    | '/costing'
    | '/customers'
    | '/demand-forecast'
    | '/fabric-count'
    | '/fabrics'
    | '/facebook-feed-health'
    | '/finance'
    | '/growth-analytics'
    | '/inventory'
    | '/inventory-adjustments'
    | '/inventory-count'
    | '/inventory-inward'
    | '/ledgers'
    | '/order-search'
    | '/orders'
    | '/payroll'
    | '/production'
    | '/products'
    | '/quick-order'
    | '/return-prime'
    | '/returns'
    | '/returns-rto'
    | '/settings'
    | '/sheets-monitor'
    | '/shopify-catalog'
    | '/stock-report'
    | '/storefront'
    | '/tailor-performance'
    | '/tracking'
    | '/users'
    | '/campaigns/$campaignId'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/products/new'
    | '/returns/$returnId'
    | '/business/'
    | '/products/$productSlug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/catalog'
    | '/inward-hub'
    | '/login'
    | '/materials'
    | '/production-inward'
    | '/return-inward'
    | '/shipments'
    | '/analytics'
    | '/audiences'
    | '/bom'
    | '/campaigns'
    | '/channel-import'
    | '/channels'
    | '/costing'
    | '/customers'
    | '/demand-forecast'
    | '/fabric-count'
    | '/fabrics'
    | '/facebook-feed-health'
    | '/finance'
    | '/growth-analytics'
    | '/inventory'
    | '/inventory-adjustments'
    | '/inventory-count'
    | '/inventory-inward'
    | '/ledgers'
    | '/order-search'
    | '/orders'
    | '/payroll'
    | '/production'
    | '/products'
    | '/quick-order'
    | '/return-prime'
    | '/returns'
    | '/returns-rto'
    | '/settings'
    | '/sheets-monitor'
    | '/shopify-catalog'
    | '/stock-report'
    | '/storefront'
    | '/tailor-performance'
    | '/tracking'
    | '/users'
    | '/'
    | '/campaigns/$campaignId'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/products/new'
    | '/returns/$returnId'
    | '/business'
    | '/products/$productSlug/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/catalog'
    | '/inward-hub'
    | '/login'
    | '/materials'
    | '/production-inward'
    | '/return-inward'
    | '/shipments'
    | '/_authenticated/analytics'
    | '/_authenticated/audiences'
    | '/_authenticated/bom'
    | '/_authenticated/campaigns'
    | '/_authenticated/channel-import'
    | '/_authenticated/channels'
    | '/_authenticated/costing'
    | '/_authenticated/customers'
    | '/_authenticated/demand-forecast'
    | '/_authenticated/fabric-count'
    | '/_authenticated/fabrics'
    | '/_authenticated/facebook-feed-health'
    | '/_authenticated/finance'
    | '/_authenticated/growth-analytics'
    | '/_authenticated/inventory'
    | '/_authenticated/inventory-adjustments'
    | '/_authenticated/inventory-count'
    | '/_authenticated/inventory-inward'
    | '/_authenticated/ledgers'
    | '/_authenticated/order-search'
    | '/_authenticated/orders'
    | '/_authenticated/payroll'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/quick-order'
    | '/_authenticated/return-prime'
    | '/_authenticated/returns'
    | '/_authenticated/returns-rto'
    | '/_authenticated/settings'
    | '/_authenticated/sheets-monitor'
    | '/_authenticated/shopify-catalog'
    | '/_authenticated/stock-report'
    | '/_authenticated/storefront'
    | '/_authenticated/tailor-performance'
    | '/_authenticated/tracking'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/campaigns_/$campaignId'
    | '/_authenticated/customers_/$customerId'
    | '/_authenticated/orders_/$orderId'
    | '/_authenticated/products_/new'
    | '/_authenticated/returns_/$returnId'
    | '/_authenticated/business/'
    | '/_authenticated/products_/$productSlug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  InwardHubRoute: typeof InwardHubRoute
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRoute
  ProductionInwardRoute: typeof ProductionInwardRoute
  ReturnInwardRoute: typeof ReturnInwardRoute
  ShipmentsRoute: typeof ShipmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-inward': {
      id: '/return-inward'
      path: '/return-inward'
      fullPath: '/return-inward'
      preLoaderRoute: typeof ReturnInwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-inward': {
      id: '/production-inward'
      path: '/production-inward'
      fullPath: '/production-inward'
      preLoaderRoute: typeof ProductionInwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inward-hub': {
      id: '/inward-hub'
      path: '/inward-hub'
      fullPath: '/inward-hub'
      preLoaderRoute: typeof InwardHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tailor-performance': {
      id: '/_authenticated/tailor-performance'
      path: '/tailor-performance'
      fullPath: '/tailor-performance'
      preLoaderRoute: typeof AuthenticatedTailorPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storefront': {
      id: '/_authenticated/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof AuthenticatedStorefrontRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock-report': {
      id: '/_authenticated/stock-report'
      path: '/stock-report'
      fullPath: '/stock-report'
      preLoaderRoute: typeof AuthenticatedStockReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shopify-catalog': {
      id: '/_authenticated/shopify-catalog'
      path: '/shopify-catalog'
      fullPath: '/shopify-catalog'
      preLoaderRoute: typeof AuthenticatedShopifyCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sheets-monitor': {
      id: '/_authenticated/sheets-monitor'
      path: '/sheets-monitor'
      fullPath: '/sheets-monitor'
      preLoaderRoute: typeof AuthenticatedSheetsMonitorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/returns-rto': {
      id: '/_authenticated/returns-rto'
      path: '/returns-rto'
      fullPath: '/returns-rto'
      preLoaderRoute: typeof AuthenticatedReturnsRtoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/return-prime': {
      id: '/_authenticated/return-prime'
      path: '/return-prime'
      fullPath: '/return-prime'
      preLoaderRoute: typeof AuthenticatedReturnPrimeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quick-order': {
      id: '/_authenticated/quick-order'
      path: '/quick-order'
      fullPath: '/quick-order'
      preLoaderRoute: typeof AuthenticatedQuickOrderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order-search': {
      id: '/_authenticated/order-search'
      path: '/order-search'
      fullPath: '/order-search'
      preLoaderRoute: typeof AuthenticatedOrderSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ledgers': {
      id: '/_authenticated/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof AuthenticatedLedgersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory-inward': {
      id: '/_authenticated/inventory-inward'
      path: '/inventory-inward'
      fullPath: '/inventory-inward'
      preLoaderRoute: typeof AuthenticatedInventoryInwardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory-count': {
      id: '/_authenticated/inventory-count'
      path: '/inventory-count'
      fullPath: '/inventory-count'
      preLoaderRoute: typeof AuthenticatedInventoryCountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory-adjustments': {
      id: '/_authenticated/inventory-adjustments'
      path: '/inventory-adjustments'
      fullPath: '/inventory-adjustments'
      preLoaderRoute: typeof AuthenticatedInventoryAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth-analytics': {
      id: '/_authenticated/growth-analytics'
      path: '/growth-analytics'
      fullPath: '/growth-analytics'
      preLoaderRoute: typeof AuthenticatedGrowthAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facebook-feed-health': {
      id: '/_authenticated/facebook-feed-health'
      path: '/facebook-feed-health'
      fullPath: '/facebook-feed-health'
      preLoaderRoute: typeof AuthenticatedFacebookFeedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fabrics': {
      id: '/_authenticated/fabrics'
      path: '/fabrics'
      fullPath: '/fabrics'
      preLoaderRoute: typeof AuthenticatedFabricsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fabric-count': {
      id: '/_authenticated/fabric-count'
      path: '/fabric-count'
      fullPath: '/fabric-count'
      preLoaderRoute: typeof AuthenticatedFabricCountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demand-forecast': {
      id: '/_authenticated/demand-forecast'
      path: '/demand-forecast'
      fullPath: '/demand-forecast'
      preLoaderRoute: typeof AuthenticatedDemandForecastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costing': {
      id: '/_authenticated/costing'
      path: '/costing'
      fullPath: '/costing'
      preLoaderRoute: typeof AuthenticatedCostingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channel-import': {
      id: '/_authenticated/channel-import'
      path: '/channel-import'
      fullPath: '/channel-import'
      preLoaderRoute: typeof AuthenticatedChannelImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bom': {
      id: '/_authenticated/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof AuthenticatedBomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audiences': {
      id: '/_authenticated/audiences'
      path: '/audiences'
      fullPath: '/audiences'
      preLoaderRoute: typeof AuthenticatedAudiencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/business/': {
      id: '/_authenticated/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthenticatedBusinessIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/returns_/$returnId': {
      id: '/_authenticated/returns_/$returnId'
      path: '/returns/$returnId'
      fullPath: '/returns/$returnId'
      preLoaderRoute: typeof AuthenticatedReturnsReturnIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products_/new': {
      id: '/_authenticated/products_/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders_/$orderId': {
      id: '/_authenticated/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers_/$customerId': {
      id: '/_authenticated/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns_/$campaignId': {
      id: '/_authenticated/campaigns_/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products_/$productSlug/edit': {
      id: '/_authenticated/products_/$productSlug/edit'
      path: '/products/$productSlug/edit'
      fullPath: '/products/$productSlug/edit'
      preLoaderRoute: typeof AuthenticatedProductsProductSlugEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAudiencesRoute: typeof AuthenticatedAudiencesRoute
  AuthenticatedBomRoute: typeof AuthenticatedBomRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedChannelImportRoute: typeof AuthenticatedChannelImportRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedCostingRoute: typeof AuthenticatedCostingRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDemandForecastRoute: typeof AuthenticatedDemandForecastRoute
  AuthenticatedFabricCountRoute: typeof AuthenticatedFabricCountRoute
  AuthenticatedFabricsRoute: typeof AuthenticatedFabricsRoute
  AuthenticatedFacebookFeedHealthRoute: typeof AuthenticatedFacebookFeedHealthRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGrowthAnalyticsRoute: typeof AuthenticatedGrowthAnalyticsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInventoryAdjustmentsRoute: typeof AuthenticatedInventoryAdjustmentsRoute
  AuthenticatedInventoryCountRoute: typeof AuthenticatedInventoryCountRoute
  AuthenticatedInventoryInwardRoute: typeof AuthenticatedInventoryInwardRoute
  AuthenticatedLedgersRoute: typeof AuthenticatedLedgersRoute
  AuthenticatedOrderSearchRoute: typeof AuthenticatedOrderSearchRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedQuickOrderRoute: typeof AuthenticatedQuickOrderRoute
  AuthenticatedReturnPrimeRoute: typeof AuthenticatedReturnPrimeRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedReturnsRtoRoute: typeof AuthenticatedReturnsRtoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSheetsMonitorRoute: typeof AuthenticatedSheetsMonitorRoute
  AuthenticatedShopifyCatalogRoute: typeof AuthenticatedShopifyCatalogRoute
  AuthenticatedStockReportRoute: typeof AuthenticatedStockReportRoute
  AuthenticatedStorefrontRoute: typeof AuthenticatedStorefrontRoute
  AuthenticatedTailorPerformanceRoute: typeof AuthenticatedTailorPerformanceRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCampaignsCampaignIdRoute: typeof AuthenticatedCampaignsCampaignIdRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedReturnsReturnIdRoute: typeof AuthenticatedReturnsReturnIdRoute
  AuthenticatedBusinessIndexRoute: typeof AuthenticatedBusinessIndexRoute
  AuthenticatedProductsProductSlugEditRoute: typeof AuthenticatedProductsProductSlugEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAudiencesRoute: AuthenticatedAudiencesRoute,
  AuthenticatedBomRoute: AuthenticatedBomRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedChannelImportRoute: AuthenticatedChannelImportRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedCostingRoute: AuthenticatedCostingRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDemandForecastRoute: AuthenticatedDemandForecastRoute,
  AuthenticatedFabricCountRoute: AuthenticatedFabricCountRoute,
  AuthenticatedFabricsRoute: AuthenticatedFabricsRoute,
  AuthenticatedFacebookFeedHealthRoute: AuthenticatedFacebookFeedHealthRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGrowthAnalyticsRoute: AuthenticatedGrowthAnalyticsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInventoryAdjustmentsRoute:
    AuthenticatedInventoryAdjustmentsRoute,
  AuthenticatedInventoryCountRoute: AuthenticatedInventoryCountRoute,
  AuthenticatedInventoryInwardRoute: AuthenticatedInventoryInwardRoute,
  AuthenticatedLedgersRoute: AuthenticatedLedgersRoute,
  AuthenticatedOrderSearchRoute: AuthenticatedOrderSearchRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedQuickOrderRoute: AuthenticatedQuickOrderRoute,
  AuthenticatedReturnPrimeRoute: AuthenticatedReturnPrimeRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedReturnsRtoRoute: AuthenticatedReturnsRtoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSheetsMonitorRoute: AuthenticatedSheetsMonitorRoute,
  AuthenticatedShopifyCatalogRoute: AuthenticatedShopifyCatalogRoute,
  AuthenticatedStockReportRoute: AuthenticatedStockReportRoute,
  AuthenticatedStorefrontRoute: AuthenticatedStorefrontRoute,
  AuthenticatedTailorPerformanceRoute: AuthenticatedTailorPerformanceRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCampaignsCampaignIdRoute: AuthenticatedCampaignsCampaignIdRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedReturnsReturnIdRoute: AuthenticatedReturnsReturnIdRoute,
  AuthenticatedBusinessIndexRoute: AuthenticatedBusinessIndexRoute,
  AuthenticatedProductsProductSlugEditRoute:
    AuthenticatedProductsProductSlugEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CatalogRoute: CatalogRoute,
  InwardHubRoute: InwardHubRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  ProductionInwardRoute: ProductionInwardRoute,
  ReturnInwardRoute: ReturnInwardRoute,
  ShipmentsRoute: ShipmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
