/**
 * Sync Configuration Index
 *
 * Central export for all sync-related configurations.
 */

// Shopify Sync
export {
    SHOPIFY_BATCH_SIZE,
    SHOPIFY_CONCURRENCY_LIMIT,
    SHOPIFY_PREVIEW_METAFIELD_LIMIT,
    SHOPIFY_LOOKBACK_DAYS,
    ORDER_UPDATE_TRIGGER_FIELDS,
    SKIP_CUSTOMERS_WITHOUT_ORDERS,
    REQUIRE_CUSTOMER_EMAIL,
    SHOPIFY_CACHE_STALE_DAYS,
    SHOPIFY_CACHE_CLEANUP_BATCH_SIZE,
    SHOPIFY_SYNC,
    SYNC_WORKER_CONFIG,
    FULL_DUMP_CONFIG,
    type OrderUpdateTriggerField,
} from './shopify.js';

// iThink Sync
export {
    ITHINK_TRACKING_BATCH_SIZE,
    ITHINK_API_TIMEOUT_MS,
    ITHINK_API_RETRIES,
    ITHINK_RETRY_DELAY_MS,
    ITHINK_SYNC_INTERVAL_MINUTES,
    ITHINK_BATCH_DELAY_MS,
    ITHINK_STARTUP_DELAY_MS,
    ITHINK_SYNC_STATUSES,
    ITHINK_TERMINAL_STATUSES,
    ITHINK_BACKFILL_DEFAULT_DAYS,
    ITHINK_BACKFILL_DEFAULT_LIMIT,
    ITHINK_SYNC,
    CIRCUIT_BREAKER_CONFIG,
    ORDER_LOCK_CONFIG,
    shouldSyncStatus,
    isTerminalTrackingStatus,
} from './ithink.js';
