/**
 * Sync Configuration Index
 *
 * Central export for all sync-related configurations.
 */

// Shopify Sync
export {
    SHOPIFY_BATCH_SIZE,
    SHOPIFY_CONCURRENCY_LIMIT,
    SHOPIFY_PREVIEW_METAFIELD_LIMIT,
    SHOPIFY_LOOKBACK_DAYS,
    ORDER_UPDATE_TRIGGER_FIELDS,
    SKIP_CUSTOMERS_WITHOUT_ORDERS,
    REQUIRE_CUSTOMER_EMAIL,
    SHOPIFY_CACHE_STALE_DAYS,
    SHOPIFY_CACHE_CLEANUP_BATCH_SIZE,
    SYNC_WORKER_CONFIG,
    FULL_DUMP_CONFIG,
    type OrderUpdateTriggerField,
} from './shopify.js';

// iThink Sync
export {
    ITHINK_TRACKING_BATCH_SIZE,
    ITHINK_API_TIMEOUT_MS,
    ITHINK_API_RETRIES,
    ITHINK_RETRY_DELAY_MS,
    ITHINK_SYNC_INTERVAL_MINUTES,
    ITHINK_BATCH_DELAY_MS,
    ITHINK_STARTUP_DELAY_MS,
    ITHINK_SYNC_STATUSES,
    ITHINK_TERMINAL_STATUSES,
    ITHINK_BACKFILL_DEFAULT_DAYS,
    ITHINK_BACKFILL_DEFAULT_LIMIT,
    CIRCUIT_BREAKER_CONFIG,
    ORDER_LOCK_CONFIG,
    shouldSyncStatus,
    isTerminalTrackingStatus,
} from './ithink.js';

// Google Sheets Offload
export {
    ENABLE_SHEET_OFFLOAD,
    ENABLE_SHEET_DELETION,
    ORDERS_MASTERSHEET_ID,
    OFFICE_LEDGER_ID,
    BARCODE_MASTERSHEET_ID,
    ENABLE_FABRIC_LEDGER_PUSH,
    FABRIC_LEDGER_PUSH_INTERVAL_MS,
    LEDGER_TABS,
    LIVE_TABS,
    INVENTORY_TAB,
    MASTERSHEET_TABS,
    BARCODE_TABS,
    INWARD_COLS,
    INWARD_LIVE_COLS,
    OUTWARD_LIVE_COLS,
    OUTWARD_COLS,
    ORDERS_OUTWARD_COLS,
    ORDERS_OUTWARD_OLD_COLS,
    MASTERSHEET_OUTWARD_COLS,
    BALANCE_COLS,
    BARCODE_MAIN_COLS,
    FABRIC_BALANCES_COLS,
    FABRIC_BALANCES_HEADERS,
    FABRIC_BALANCES_COUNT_DATETIME,
    INWARD_SOURCE_MAP,
    DEFAULT_INWARD_REASON,
    OUTWARD_DESTINATION_MAP,
    DEFAULT_OUTWARD_REASON,
    REF_PREFIX,
    OFFLOAD_NOTES_PREFIX,
    OFFLOAD_INTERVAL_MS,
    STARTUP_DELAY_MS,
    API_CALL_DELAY_MS,
    API_MAX_RETRIES,
    BATCH_SIZE,
    GOOGLE_SERVICE_ACCOUNT_PATH,
    SHEETS_API_SCOPE,
    ORIGINAL_BALANCE_FORMULA,
    PHASE2_BALANCE_FORMULA,
    LIVE_BALANCE_FORMULA_TEMPLATE,
    RETURN_EXCHANGE_COLS,
    RETURN_SOURCE_MAP,
    DEFAULT_RETURN_SOURCE,
} from './sheets.js';

// Google Drive Finance Sync
export {
    DRIVE_FINANCE_FOLDER_ID,
    DRIVE_API_SCOPE,
    DRIVE_API_CALL_DELAY_MS,
    DRIVE_API_MAX_RETRIES,
    DRIVE_SYNC_BATCH_SIZE,
    DRIVE_UNLINKED_FOLDER_NAME,
    getFinancialYear,
} from './drive.js';

// Facebook Feed Health
export {
    FACEBOOK_FEED_URL,
    FEED_HEALTH_CACHE_DURATION_MS,
    PRICE_TOLERANCE,
    DB_CHUNK_SIZE,
} from './facebookFeed.js';
